### ISSUE TITLE
Add version requirements

### ISSUE THREAD

**Issue by DamienCassou** [ericdanan/counsel-projectile#1]
I guess you have to specify minimum versions for counsel and projectile in:

``` emacs-list
;; Package-Requires: ((counsel) (projectile))
```

**Comment by ericdanan** [comment]
Thank you.

Do you have any idea which versions I should require?

`helm-projectile` requires `projectile "0.13.0"`, so by best guess would be to copy that.

For `counsel` I can't find anything to copy, and in fact I don't find a version number in `counsel.el`.

**Comment by DamienCassou** [comment]
ericdanan notifications@github.com writes:

> Thank you.
> 
> Do you have any idea which versions I should require?
> 
> `helm-projectile` requires `projectile "0.13.0"`, so by best guess would be to copy that.
> 
> For `counsel` I can't find anything to copy, and in fact I don't find a version number in `counsel.el`.

from http://melpa.org/#/counsel: 20160411

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by ericdanan** [comment]
Thanks, I used that.

**Comment by purcell** [comment]
Please don't depend on snapshot versions, because that stops things working for people who prefer to use MELPA Stable only. In the case of counsel, I think you want "0.7", as shown here: http://stable.melpa.org/#/counsel

**Comment by ericdanan** [comment]
OK I changed the version to "0.7.0" as shown on the MELPA Stable page.
Thanks.
