### ISSUE TITLE
Hide files in counsel-projectile-find-file

### ISSUE THREAD

**Issue by CSRaghunandan** [ericdanan/counsel-projectile#10]
Hello,

I stumbled upon `counsel-find-file-ignore-regexp` today in [this discussion](https://github.com/abo-abo/swiper/issues/685#issue). Is it possible to get similar functionality for `counsel-projectile-find-file` where I can ignore some files like dot files or files beginning with # or ~  by setting an `ignore-regexp` for `counsel-projectile-find-file`

**Comment by CSRaghunandan** [comment]
I solved this problem using [kaushalmodi's](https://github.com/kaushalmodi/) config :- 

```
https://github.com/kaushalmodi/(defconst modi/ag-arguments
    '("--nogroup" ; mandatory argument for ag.el as per https://github.com/Wilfred/ag.el/issues/41
      "--skip-vcs-ignores" ; Ignore files/dirs ONLY from `.agignore'
      "--numbers" ; line numbers
      "--smart-case"
      "--follow") ; follow symlinks
    "Default ag arguments used in the functions in `ag', `counsel' and `projectile'
     packages.")

  ;; Use `ag' all the time if available
  (defun modi/advice-projectile-use-ag ()
    "Always use `ag' for getting a list of all files in the project."
    (mapconcat 'identity
           (append '("\\ag") ; used unaliased version of `ag': \ag
               modi/ag-arguments
               '("-0" ; output null separated results
             "-g ''")) ; get file names matching the regex '' (all files)
           " "))
  (when (executable-find "ag")
    (advice-add 'projectile-get-ext-command :override
        #'modi/advice-projectile-use-ag))
```

**Comment by ericdanan** [comment]
FYI, `counsel-projectile-find-file` now uses `counsel--find-file-matcher`, so I think you should now be able to do what you want (make sure to update ivy before testing).

Also `counsel-projectile-switch-to-buffer` now uses `ivy--switch-buffer-matcher`. So I hope you can now have a consistent experience between ivy / counsel and counsel-projectile.
