### ISSUE TITLE
(wrong-type-argument arrayp projectile-ripgrep)

### ISSUE THREAD

**Issue by shitikanth** [ericdanan/counsel-projectile#101]
ff902d5cd seems to have made `(counsel-projectile-mode)` depend on `projectile-ripgrep`.

Expected behaviour: one should be able to use `counsel-projectile-mode` without having to install `projectile-ripgrep`.

**Comment by ericdanan** [comment]
`projectile-ripgrep` is not a package that you have to install, it's a command defined in the projectile package, provided you have a recent enough version of that package. Can you update projectile and let me know if you still experience this issue?

**Comment by shitikanth** [comment]
Solved. Thanks.
