### ISSUE TITLE
Error (use-package): counsel-projectile/:config: Key sequence s i starts with non-prefix key s

### ISSUE THREAD

**Issue by Opioid** [ericdanan/counsel-projectile#107]
Roughly since projectile 1.0, every time I start emacs, I get the following message:

_Error (use-package): counsel-projectile/:config: Key sequence s i starts with non-prefix key s_

Although I don't really understand the error message I know that it is related to this line in my config:
`(define-key projectile-command-map (kbd "s") 'projectile-ripgrep)`
I want to keep this line because it makes searches in a project easier if you only ever use one search mechanism.
Is there a way to get rid of this error message?

**Comment by ericdanan** [comment]
When counsel-projectile mode is turned on, the key bindings stored in `counsel-projectile-key-bindings` are added to `projectile-command-map`. By default, there is a key binding `si` for `counsel-projectile-git-grep`. But if you have previously set `s` as a key binding for `counsel-rg`, then the `si` key binding generates an error because the `s` key can no longer be used as a prefix key. To remove the error, you should remove the `si` key binding from `counsel-projectile-key-bindings` before calling `counsel-projectile-mode` (but after loading counsel-projectile). The following should do:
```el
(setcdr (assoc "si" counsel-projectile-key-bindings) nil)
```

**Comment by Opioid** [comment]
I tried the following and it didn't work.
```
(use-package counsel-projectile
  :config
  (setcdr (assoc "si" counsel-projectile-key-bindings) nil)
  (counsel-projectile-mode))
```

**Comment by ericdanan** [comment]
Are you still getting the same error message about the `si` keybinding? Could you post your entire projectile / counsel-projectile setup?

**Comment by Opioid** [comment]
Yes, same error.
```
(use-package projectile
  :ensure t
  :config
  (projectile-mode)
  (setq projectile-mode-line-function 'my-projectile-mode-line)
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
  (define-key projectile-command-map (kbd "s") 'projectile-ripgrep)
  :bind (([f5] . my-projectile-run-project)
		 ([f7] . my-projectile-compile-project))
  :custom
  (projectile-indexing-method 'alien))

(use-package counsel-projectile
  :config
  (setcdr (assoc "si" counsel-projectile-key-bindings) nil)
  (counsel-projectile-mode))
```
Produces  _Error (use-package): counsel-projectile/:config: Key sequence s i starts with non-prefix key s_

**Comment by ericdanan** [comment]
OK my bad, setting the `cdr` to `nil` is not enough, you need to entirely remove the key binding from the list. So please try this in place of the `setcdr` form:
```el
(setq counsel-projectile-key-bindings
      (cl-remove-if (lambda (kb)
		      (and (stringp (car kb))
			   (string-prefix-p "s" (car kb))))
		    counsel-projectile-key-bindings))
```
It will actually remove all key bindings starting with "s", in case more would be added in the future.

A perhaps simple solution could be to define the "s" keybinding in counsel-projectile rather that in projectile. That is, you would remove the second `define-key` and replace the `setcdr` form with:
```el
(add-to-list 'counsel-projectile-key-bindings '("s" . counsel-projectile-rg) t)
```

**Comment by Opioid** [comment]
I went with your second suggestion. Works nicely, thanks!
