### ISSUE TITLE
counsel-projectile-switch-project cannot open file

### ISSUE THREAD

**Issue by goofansu** [ericdanan/counsel-projectile#11]
alway says "You're not in a project".

FYI, I'm using the most recent spacemacs develop branch.

**Comment by ericdanan** [comment]
Hello,

I can't reproduce the problem in emacs, I'm not familiar with spacemacs. So it's hard to guess what goes wrong, so let me ask a few basic questions:
- Are you using the latest versions of projectile and counsel-projectile?
- Do you use any custom setup for these packages?
- Do you setup counsel-projectile with `counsel-projectile-on`?
- What is your `projectile-switch-project-action`?

**Comment by goofansu** [comment]
Hi,

I can only answer two questions:

> Are you using the latest versions of projectile and counsel-projectile?

Yes, I'm using melpa version `counsel-projectile-20160916.1319` and `projectile-20160921.902`

> What is your projectile-switch-project-action?

counsel-projectile-find-file

**Comment by goofansu** [comment]
I'll close this and open one on spacemacs
