### ISSUE TITLE
Errors in non-projectile directory

### ISSUE THREAD

**Issue by seagle0128** [ericdanan/counsel-projectile#111]
GNU Emacs 26.1
macOS 10.14

`projectile-find-file` works fine, but `counsel-projectile-find-file` returns error.

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^/tmp_mnt/" nil)
  abbreviate-file-name(nil)
  projectile-locate-dominating-file(nil ".git")
  projectile-project-vcs(nil)
  projectile-dir-files-alien(nil)
  projectile-project-files(nil)
  projectile-current-project-files()
  counsel-projectile-find-file(nil)
  funcall-interactively(counsel-projectile-find-file nil)
  call-interactively(counsel-projectile-find-file nil nil)
  command-execute(counsel-projectile-find-file)
```

**Comment by ericdanan** [comment]
I can't reproduce this error. When I call `projectile-find-file` or `counsel-projectile-find-file` from a non-project directory, I'm first prompted to select a project from which to find a file (this is the default behavior in projectile and counsel-projectile replicates it). Could you update projectile and counsel-projectile and try again? If you still get the error, could you post your projectile and counsel-projectile setup?

**Comment by seagle0128** [comment]
I updated all packages and seems the issue is gone. 
Thanks for your help.
