### ISSUE TITLE
counsel-projectile-rg: truncated prompt

### ISSUE THREAD

**Issue by manuel-uberti** [ericdanan/counsel-projectile#112]
Hi,

with latest `ivy/counsel` and `counsel-projectile`  from MELPA, this is what I see when I use `counsel-projectile-rg`:

![1](https://user-images.githubusercontent.com/8199224/48977388-92e5db00-f099-11e8-9fa8-b1c1cdca3aca.png)

And this is the prompt for `counsel-rg`:

![2](https://user-images.githubusercontent.com/8199224/48977393-a133f700-f099-11e8-809f-5539aaca17fc.png)

These are some details about my system, in case you need them:

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-11-24

Repository revision: 4ef9bcd0ff0eccb0c0810f43370eaa76aef2f4ec
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 2 hours, 0 minutes, 29 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by drrlvn** [comment]
Not only is the prompt truncated, searching doesn't work at all.

**Comment by manuel-uberti** [comment]
Well, it actually works for me if I hit <kbd>SPACE</kbd> and start typing.

**Comment by ericdanan** [comment]
Thanks for the reports. The problem occurred after a recent changed in counsel. Please update and test, it should work now.

**Comment by manuel-uberti** [comment]
Thank you, it works now.
