### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by skuro** [ericdanan/counsel-projectile#119]
There was no release in MELPA stable after v0.2.0, maybe it's time for a new release?

**Comment by ericdanan** [comment]
Yes I would like to tag a new counsel-projectile release, but I first have to wait for a new ivy release because the current counsel-projectile code depends on ivy commits that are posterior to the last ivy release (0.10.0).

**Comment by ericdanan** [comment]
I just tagged a new counsel-projectile release 0.3.0.
