### ISSUE TITLE
Maybe tag a release?

### ISSUE THREAD

**Issue by mdorman** [ericdanan/counsel-projectile#120]
Since 0.2.0 no longer works correctly with projectile > 1.0, it seems like it would be good to tag a recent version as a new release so anyone using melpa-stable can have a working setup...

**Comment by ericdanan** [comment]
See #119. Yes I would like to tag a new counsel-projectile release, but I first have to wait for a new ivy release because the current counsel-projectile code depends on ivy commits that are posterior to the last ivy release (0.10.0).

**Comment by paulbdavis** [comment]
The only thing I have to do to get the non-stable version of this to work with `ivy` 0.10.0 is add a missing definition before loading `counsel-projectile`

```elisp
  (defvar ivy-highlight-grep-commands nil
    "List of counsel grep-like commands.")
```

EDIT: Not to say that other stuff isn't broken, but this allows it to at least load up

**Comment by paulbdavis** [comment]
Looks like this is being worked on [here](https://github.com/abo-abo/swiper/issues/1664)

**Comment by ericdanan** [comment]
Thanks @pauldavis. As soon as I see a new ivy/counsel release I will tag a new counsel-projectile one.

**Comment by paulbdavis** [comment]
@ericdanan It looks like 0.11.0 is now on melpa stable, it should be in GNU elpa soon as well

**Comment by ericdanan** [comment]
Thanks. I just tagged a new counsel-projectile release 0.3.0.
