### ISSUE TITLE
duplicate counsel-projectile-rg results in Emacs-25

### ISSUE THREAD

**Issue by rski** [ericdanan/counsel-projectile#122]
In emacs25, trim string right has no argument for the regex. counsel-projectile does:

`string-trim-right counsel-rg-base-command " \\.")`

To strip the trailing spacedot in counsel-rg-base-command:

`rg -S --no-heading --line-number --color never %s .`

However, this doesn't work, so as far  as I can tell, it uses the original base-command, which results in me seeing duplicate results when calling counsel-projectile-rg. This problem doesn't exist in Emacs 26, which has an argument. 

If I have some time I'll send a patch to fix this. If you don't want to support Emacs-25 that's cool, I  should be able to patch string-trim-right locally in my config for Emacs-25.

**Comment by ericdanan** [comment]
Just copied the emacs 26 `string-trim-right` function into counsel-projectile, please let me know if that works.

**Comment by rski** [comment]
it does, thanks a lot!
