### ISSUE TITLE
counsel-projectile-grep-initial-input error

### ISSUE THREAD

**Issue by knusprjg** [ericdanan/counsel-projectile#125]
Hi,

I wanted to customize the initial input of the grep. Changing it with `customize-group` to any of the proposed values leads me to errors like this:

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp '(thing-at-point 'symbol t))
  ivy--split-negation('(thing-at-point 'symbol t))
  ivy--regex-plus('(thing-at-point 'symbol t))
[...]
  counsel-git-grep-history :caller counsel-git-grep)
  counsel-git-grep(nil '(thing-at-point 'symbol t))
  counsel-projectile-git-grep(nil)
  counsel-projectile-grep()
  funcall-interactively(counsel-projectile-grep)
  call-interactively(counsel-projectile-grep nil nil)
  command-execute(counsel-projectile-grep)
```

`customize-group` adds the following to `custom.el`:

```elisp
(custom-set-variables
[...]
 '(counsel-projectile-grep-initial-input (quote (quote (thing-at-point (quote symbol) t))))
```

Is this somehow a real issue or just connected to my setup? This is probably easy to debug for someone with proper lisp knowledge, unfortunately I'm not that one yet ;) So please let me know if you need further informations and keep up the great work y'all!

**Comment by ericdanan** [comment]
Thanks for reporting. Should be fixed now. Please update counsel-projectile and test.
