### ISSUE TITLE
Treemacs support

### ISSUE THREAD

**Issue by jdemilledt** [ericdanan/counsel-projectile#128]
I used to have `treemacs-add-and-display-current-project` as my Projectile action, but I can't do that anymore with `counsel-projectile`. How do I set my own actions and/or can you add a Treemacs option?

**Comment by ericdanan** [comment]
I'm not using treemacs, but I imagine the following would work (let me know if not):

```el
(defun counsel-projectile-switch-project-action-treemacs (project)
  "Open `treemacs' and add PROJECT root to the workspace."
  (let ((projectile-switch-project-action 'treemacs-add-and-display-current-project))
    (counsel-projectile-switch-project-by-name project)))
```

The following will add this action, assign it the `Y` key and set it as default:
```el
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((add ("Y" counsel-projectile-switch-project-action-treemacs "open project in treemacs") 1)))

**Comment by ericdanan** [comment]
Please reopen if needed.
