### ISSUE TITLE
Installation with counsel from elpa

### ISSUE THREAD

**Issue by hpdeifel** [ericdanan/counsel-projectile#130]
I'd like to install `counsel-projectile` from melpa-stable without installing `counsel` from melpa/melpa-stable and keep my counsel installation from GNU Elpa. Unfortunately, there is no dedicated `counsel` package in elpa and the feature is provided by the package `ivy` instead.

I don't know if this is possible with the emacs package system, but maybe someone has an idea :smile:

**Comment by hpdeifel** [comment]
To clarify: The problem is that `counsel-projectile` declares a dependency on `counsel`, which is not provided by GNU elpa

**Comment by ericdanan** [comment]
Hi, sorry for the slow reply. I understand the issue but I can't think of a solution. It seems to me that I have to declare a dependency on counsel on MELPA(-stable), otherwise it won't work for users who load counsel from there. I don't know why counsel is distinct from ivy on MELPA(-stable) and not on ELPA and the only suggestion I can offer is to ask @abo-abo about this.

Out of curiosity, why do you not want to load counsel from MELPA-stable ?

**Comment by abo-abo** [comment]
For maintenance convenience, `ivy`, `swiper`, and `counsel` are in the same repo. I wouldn't want to change this.

MELPA provides an easy way to create multiple packages from the same repo, while GNU ELPA does not. If it were easy to do, I wouldn't mind splitting into three packages on GNU ELPA as well.

**Comment by ericdanan** [comment]
I see, thanks for the explanation @abo-abo.

@hpdeifel I'm afraid I don't see how to address your request given that counsel is separated from ivy on MELPA but not on ELPA. Perhaps it is possible in your local setup to "tell emacs" that counsel is here before the dependencies for counsel-projectile are checked, I'm not sure.

I can leave this open for some time in case someone has an idea.

**Comment by hpdeifel** [comment]
The only thing I could think of would be to release a dummy package for `counsel` on ELPA that exists only to depend on `ivy`; no idea if that is possible with ELPA/package.el.

It's probably not worth the trouble, I can just use MELPA-stable. The reasons why I'd like to install as many packages from ELPA are that it is centrally developed, has signed packages and encourages proper releases, leading to better security and stability than MELPA (to me, at least).

**Comment by abo-abo** [comment]
I could theoretically rename `ivy` to something like `ivy-swiper-counsel` on GNU ELPA. But then the old versions of `ivy` would still be on GNU ELPA, possibly leading to even more confusion.

**Comment by baerrach** [comment]
@hpdeifel Have you considered using https://github.com/raxod502/straight.el as an alternative package manager?

For security and stability I'd much rather depend on the git repo than an external package.

I can easily pin versions directly with git hashes and not futz with reverting packages.

And when I decide to contribute I've got the source right there ready for merge requests to flow in.

**Comment by hpdeifel** [comment]
@baerrach Thanks for the suggestion. I'm aware of straight.el, but I'm not sure if it fits my workflow. I will certainly try it out at some point.

**Comment by ericdanan** [comment]
I'm going to close this issue, feel free to reopen if any new idea comes out.
