### ISSUE TITLE
Option to use counsel-projectile-rg prefilled with word under cursor?

### ISSUE THREAD

**Issue by zzantares** [ericdanan/counsel-projectile#131]
Hello, I'm wondering if it is possible to use `counsel-projectile-rg` by automatically searching for the word under the cursor? didn't see a way to do that in the documentation but it seems like a a common thing to do, is this supported? if not, can be added?

Thanks!

**Comment by ericdanan** [comment]
Yes it is supported, you just need to customize the variable `counsel-projectile-rg-initial-input`. See the documentation [here](https://github.com/ericdanan/counsel-projectile#initial-input-for-the-project-search-commands).

**Comment by zzantares** [comment]
Yes that was it!, thanks!
