### ISSUE TITLE
Update the counsel dependency to 0.12.0

### ISSUE THREAD

**Issue by lafrenierejm** [ericdanan/counsel-projectile#132]
Counsel 0.12.0 was tagged in https://github.com/abo-abo/swiper/commit/85d1e2e779ca92e6ef8e47d08f866b13d4d87aee.

**Comment by lafrenierejm** [comment]
I didn't realize that the versions in Emacs's `Package-Requires` are the _minimum_ versions.  I believe this issue can be safely ignored, and I apologize for the noise.

**Comment by ericdanan** [comment]
Indeed you can have a newer version than the required one. That being said it's better to update the dependency when a new version comes out, so I just did it. Thanks.

**Comment by lafrenierejm** [comment]
> it's better to update the dependency when a new version comes out

Out of curiosity, why is that?  I would have thought that specifying the minimum required version would be preferable.

**Comment by ericdanan** [comment]
Yes it might be subjective actually. Indeed keeping the minimum requirement to 0.11 allows to support users who don't want to update to 0.12. But on the other hand I don't see any harm in updating ivy / counsel to the latest stable version, and I find it simpler in case counsel-projectile would rely on some code from the latest version.

**Comment by lafrenierejm** [comment]
That's fair.  Thank you for taking time to respond.  And thank you for the excellent package!
