### ISSUE TITLE
counsel-projectile-grep to ivy-occur not working with fuzzy matching

### ISSUE THREAD

**Issue by knusprjg** [ericdanan/counsel-projectile#134]
counsel-projectile(-git)-grep with ivy--regex-fuzzy is working as expected. Howevery something goes wrong when trying to channel the results from the minibuffer to ivy-occur. Example:

counsel-projectile-grep for "test" -> ivy-occur results:
```
-*- mode:grep; default-directory: "~/.emacs.d/" -*-

1 candidates:
./fatal: -e option, '\(t\)[^e?': Unmatched [ or [^
```
I guess this is an issue of escapping the regular expression used for fuzzy matching. swiper/counsel-projectile-find-file et al seem to do it properly.

**Comment by ericdanan** [comment]
I can reproduce the issue with `counsel-projectile-git-grep`, but for me it also affects `counsel-git-grep` (which makes sense since the former relies on the latter). Could you check whether this is also the case for you? If so then it should be fixed in counsel rather than counsel-projectile.

**Comment by knusprjg** [comment]
Yes, same for me. Sorry, didn't notice that before. I will move this case to counsel. :) Thanks, and keep up the great work!
