### ISSUE TITLE
Feature Request - support for fzf

### ISSUE THREAD

**Issue by peterhoeg** [ericdanan/counsel-projectile#136]
```counsel-fzf``` already makes coursel work with fzf but it runs relative to the current directory so having counsel-projectile support it would be awesome.

The reason for needing is fzf support is that the projectile native indexing is crazy slow  and using the hybrid/alien indexing methods doesn't work properly across sub-projects/sub-modules while fzf is wickedly fast *and* gives us all we need.

**Comment by ericdanan** [comment]
I don't use this regularly but just tried and `counsel-fzf` does run from the project root by default for me. This seems to be the default behavior if you didn't modify the value of `counsel-fzf-dir-function`. Or am I misunderstanding your request?

**Comment by peterhoeg** [comment]
Ahh, it's actually a projectile issue with nested repositories. You're right. I'll take the issue upstream instead.
