### ISSUE TITLE
DWIM for opening project files outside of projectile projects?

### ISSUE THREAD

**Issue by wpcarro** [ericdanan/counsel-projectile#137]
Say I'm in `/tmp/path/somewhere.txt`, and I'd like to search for and open a file that resides in a version controlled project `~/programming/my-project`.

Does a command exist to search `~/programming/my-project` from `/tmp/path/somewhere.txt`? I've tried a few commands, but nothing seems to be what I need.

Here's what I'm currently trying:

```elisp
(defun bookmark/handle-directory-dwim (path)
  "Open PATH as either a project directory or a regular directory.
If PATH is `projectile-project-p', open with `counsel-projectile-find-file'.
Otherwise, open with `counsel-find-file'."
  (if (projectile-project-p path)
      (counsel-projectile-find-file path)
    (let ((ivy-extra-directories nil))
      (counsel-find-file path))))
```

The problem is that `counsel-projectile-find-file` doesn't accept `path`, since it seem designed to be called interactively using the current project is it's context. How might I compose a version that accepts a project as an argument and search that project's files using counsel projectile?

**Comment by wpcarro** [comment]
Update: The following seems to be working for me, but I cannot help but think that I should be consuming an existing function that would be better suited for this task.


```elisp
(defun bookmark/handle-directory-dwim (path)
  "Open PATH as either a project directory or a regular directory.
If PATH is `projectile-project-p', open with `counsel-projectile-find-file'.
Otherwise, open with `counsel-find-file'."
  (if (projectile-project-p path)
      (with-temp-buffer
        (cd (projectile-project-p path))
        (call-interactively #'counsel-projectile-find-file))
    (let ((ivy-extra-directories nil))
      (counsel-find-file path))))
```

Does this feel hackish to anyone else?

**Comment by ericdanan** [comment]
Hello,

Is `counsel-projectile-switch-project` what you are looking for?

**Comment by wpcarro** [comment]
`counsel-projectile-switch-project` doesn't accept a filepath (i.e. `path` from above). If I understand it correctly, it's intended to be used as an interactive command that presents an ivy buffer for choosing between projects that `projectile` already recognizes.

**Comment by ericdanan** [comment]
I see. Then how about `counsel-projectile-switch-project-action`?

**Comment by wpcarro** [comment]
@ericdanan seems to be doing the trick. Thanks.
