### ISSUE TITLE
counsel-projectile-mode won't enable on startup using the conventional method

### ISSUE THREAD

**Issue by SudoerReodus** [ericdanan/counsel-projectile#143]
Hey,

Adding:

    (require 'counsel-projectile) 
    (counsel-projectile-mode)
to my `.emacs` file won't enable counsel-projectile on startup ... the mode gets enabled by it won't trigger when using projectile's commands (they will still try to use `ido`)
manually disabling and re-enabling it after startup (i.e. doing `M-x counsel-projectile-mode` two times) solves the problem.

**Comment by SudoerReodus** [comment]
Adding `(add-hook 'emacs-startup-hook 'counsel-projectile-mode)` to the `.emacs` file fixes the problem. please add this to the `README`.

Thanks

**Comment by ericdanan** [comment]
Hello,

Adding `(counsel-projectile-mode)' to your init file should be sufficient, and it is for me, so it would be good to understand why it is not for you. Could you post your entire projectile / counsel-projectile setup? Are the two packages up to date? What is your emacs version?

**Comment by SudoerReodus** [comment]
sure

GNU Emacs 26.3

the packages are up to date, but I have melpa-stable at higher priority if that affects it in any way.

[dotemacs.txt](https://github.com/ericdanan/counsel-projectile/files/4083780/dotemacs.txt)

**Comment by ericdanan** [comment]
Thanks. I'm not sure but you test whether commenting out your helm-projectile or treemacs-projectile settings fixes your issue?

**Comment by SudoerReodus** [comment]
yes, commenting this line, understandably solved the problem:

`(helm-projectile-off)`

sorry to take your time

I will close the issue
