### ISSUE TITLE
switch-project-action run-eshell fails

### ISSUE THREAD

**Issue by jkozak** [ericdanan/counsel-projectile#144]
setting `counsel-projectile-switch-project-action`  to `counsel-projectile-switch-project-action-run-eshell` causes project switching to fail.  This is because `projectile-run-eshell` now has a single, mandatory argument yet is called with zero args.  Looking at the code this probably also applies to the otherr shells.

I fixed it temporarily by creating a variant action:
```
(defun jk/counsel-projectile-switch-project-action-run-eshell (project)
      "Invoke `eshell' from PROJECT's root."
      (let ((projectile-switch-project-action
             #'(lambda () (projectile-run-eshell "")) ))
        (counsel-projectile-switch-project-by-name project)))
```

and using that instead.

**Comment by ericdanan** [comment]
Thanks for reporting. It should work now, please update counsel-projectile and test.

**Comment by jkozak** [comment]
This fixes my problem - thanks.
