### ISSUE TITLE
[Feature] counsel-projectile-org-capture specify order of concatenation to templates.

### ISSUE THREAD

**Issue by mohkale** [ericdanan/counsel-projectile#146]
By default counsel-projectile-org-capture-templates is inserted before org-capture-templates. I'd prefer if they were inserted after; so I'd like to suggest an option to specify the order in which the two lists are concatenated. Something like:

```elisp
(setq counsel-projectile-org-capture-templates-first-p nil)
```

or something to that affect.

**Comment by ericdanan** [comment]
Thanks for suggestion. I created that variable so you can customize it to place project templates at the end.

**Comment by mohkale** [comment]
much appreciated, thank you 😄.
