### ISSUE TITLE
Feature request: Support changing action after choosing project

### ISSUE THREAD

**Issue by schellj** [ericdanan/counsel-projectile#149]
My apologies if this is already supported somehow that I missed, but it would be nice if you could switch to a different action after having choosing a project with `counsel-projectile-switch-project`.  I know that you can `M-o` before choosing a project to use an action other than the default action, but my issue is wanting to use a different action after I've already chosen a project.  

E.g., I chose a project from `counsel-projectile-switch-project` and the default `counsel-projectile-find-file` is invoked, but I belatedly realize that I actually want to search within the project instead of finding a file within the project.  Currently, I would have to `M-o p <highlight the same project> M-o s s`.  It would be nice add an `a: switch action` option to the `M-o` options that would use the already-chosen project so that I could do something like `M-o a s s` instead.

**Comment by ericdanan** [comment]
When you `M-o p`, the current project should be preselected, so it should be enough to `M-o p M-o s s` and the `M-o a s s` you would like to have would only save one `M-o`. That can still be worthwile but I am not sure how it can be done. That is, I'm not sure whether it's possible with `ivy` to skip directly to the action selection stage, skipping the candidate selection stage. I'll try to think about it.

**Comment by schellj** [comment]
@ericdanan thanks for the reply.  If there isn't an easy way to support the request, by all means, feel free to close this issue as, as you point out, it wouldn't be a major improvement.

The one additional point that I would make is that right now I find this is just a bit awkward from a UX perspective in that I have to A.) do a "switch project, use other action" sequence instead of just "switch action" and B.) remember that I can do that instead of just quitting and starting over.

**Comment by ericdanan** [comment]
I'm going to close this issue as I can't think of a good way to implement it. Thanks for the suggestion nonetheless.
