### ISSUE TITLE
show list of projects instead of showing you are not in a project for counsel-projectile-find-file

### ISSUE THREAD

**Issue by hhnr** [ericdanan/counsel-projectile#15]
Hi,

First of all, thanks for making this. I switched from helm-projectile to counsel-projectile.

I usually press `C-c p f` for `counsel-projectile-find-file` as soon as i run `emacs`. Most of the time, the path where i run emacs won't be a project, so i would want `counsel-projectile` to show list of projects (run `counsel-projectile-switch-project`) when `counsel-projectile-find-file` is invoked and currently if we are not inside a project. Instead of showing "you are not in a project", which i think is not useful because i need to run `counsel-projectile-switch-project` manually. How do i automate this behaviour? 

Thanks,
Hari

**Comment by ericdanan** [comment]
Hi,

You can call `counsel-projectile` (`C-c p SPC`) instead. It is the analogue of `helm-projectile`:  if you are inside a project it will show a list of project buffers and files, otherwise it will call `counsel-projectile-switch-project`.

**Comment by hhnr** [comment]
Okay. Thanks. It will take sometime to get used to pressing `C-c p SPC`.

**Comment by ericdanan** [comment]
You can bind `counsel-projectile` to `C-c p f` if you prefer this to `C-c p SPC`.
