### ISSUE TITLE
ivy-occur is broken in counsel-projectile-grep

### ISSUE THREAD

**Issue by bluewww** [ericdanan/counsel-projectile#150]
When you use `counsel-projectile-grep` with `projectile-use-git-grep` set to `nil`, then if you call `ivy-occur` (`C-c C-o`) on a the search minibuffer, the resulting ivy-occur buffer will be
```
1 candidates:
./grep: *search term*: No such file or directory
```

This is because `counsel-grep-like-occur` injects a case insensitivity flag with `counsel--grep-smart-case-flag` when `ivy--case-fold-p` is true. 

The contents of counsel-projectile-grep-command for me is
```
grep -rnEI [.. omitted ..] -- %s 
```
This case insensitivity flag will be pasted where 
the `%s` is. As you can see this is after the `--` which means the grep command fails.

**Comment by ericdanan** [comment]
Hello, thanks for reporting and sorry for the delay, I'll look into this ASAP but I don't have much time currently.

**Comment by ericdanan** [comment]
Should work now, please test.
