### ISSUE TITLE
counsel-projectiel-rg search doesn't work

### ISSUE THREAD

**Issue by kirill-gerasimenko** [ericdanan/counsel-projectile#152]
Hi, 
Recently I noticed that if I invoke counsel-projectile-rg and enter search text - nothing happens, it says `1 char more`.

![image](https://user-images.githubusercontent.com/3036330/81168215-dcc53700-8f96-11ea-961b-1521711ee65d.png)

If I use `projectile-rg` - it searches fine, along with other rg-related packages. 

It happens on all systems that I have - osx, windows, linux. Emacs version is ether 27 or 28. 

I see some commits recently changing the base path for search commands.. maybe these could affect this? 

Please advise.

**Comment by ericdanan** [comment]
Yes following a recent commit `rg` is no longer passed an explicit path (it is simply called from the project root), because that prevented it to handle project ignored files and directories. But I don't see why it would trigger this behavior. Was it working for you in Emacs 27/28 before this commit? Does `counsel-rg` called from the project root work?

**Comment by kirill-gerasimenko** [comment]
'counsel-rg' doesn't work from project root. 

> Was it working for you in Emacs 27/28 before this commit? 

I'll have to check that. This issue started to happen for couple of days.

**Comment by kirill-gerasimenko** [comment]
@ericdanan yes, using the commit b556ed8 makes it work again. This is a commit previous t the one you've described.

**Comment by ericdanan** [comment]
`counsel-projectile-rg` calls `counsel-rg`, so if the latter is not working then you need to solve that issue first. I don't have emacs 27/28 to test, if you have emacs 26 perhaps you could see if it works there (it does for me)? Now up to that recent commit `counsel-rg` was called with an explicit path (generally the project root) given to `rg`, so you could perhaps try the following from the projec root:

```emacs-lisp
(let ((counsel-rg-base-command (concat counsel-rg-base-command " .")))
  (counsel-rg))
```

**Comment by kirill-gerasimenko** [comment]
```
(let ((counsel-rg-base-command (concat counsel-rg-base-command " .")))
  (counsel-rg))
```

I've ran this command - and it gives me search results, so it works. Does this mean it's the problem in `counsel-rg` as you've mentioned?

**Comment by ericdanan** [comment]
It seems that `rg` needs to be given an explicit path for you. I'm not sure why that would be the case, you could perhaps test with a newer version of `rg` if you don't have the latest one, or with emacs 26.

**Comment by kirill-gerasimenko** [comment]
Got it, thanks.

For now I've just added ` .` to the rg base command's end and it works as before. 

`rg -M 240 --with-filename --no-heading --line-number --color never %s .`
