### ISSUE TITLE
Performance of counsel-projectile-find-file

### ISSUE THREAD

**Issue by sefeng211** [ericdanan/counsel-projectile#153]
Hi, using `counsel-projectile-find-file` on a large project (Firefox codebase in my case) is very janky and slow.

After typing the first few letters, the entire emacs process would hang for about 5-6 seconds before having the result listed.

**Comment by ericdanan** [comment]
Hi, is `projectile-find-file` faster than `counsel-projectile-find-file`? If so then there could a performance issue with the counsel-projectile. Otherwise the solution if any would rather be in projectile.

**Comment by sefeng211** [comment]
Yeah, I used native cache for `projectile-find-file` and it's much faster.

**Comment by ericdanan** [comment]
I'm not sure I understand. Do you mean you set `projectile-indexing-method` to `native`? Or `projectile-enable-caching` to `t`? And is `projectile-find-file` faster than `counsel-projectile-find-file` then?

**Comment by sefeng211** [comment]
I set `projectile-indexing-method` to native to gain better performance for `projectile-find-file`. Since then, `projectile-find-file` is much faster than `counsel-projectile-find-file`.

**Comment by ericdanan** [comment]
There seems to be something to investigate in counsel-projectile then. Do you have `projectile-enable-caching` set to `t`? What completion does projectile use (`projectile-completion-system`)? Can you try setting `counsel-projectile-find-file-matcher` to `nil` and calling `counsel-projectile-find-file`?

**Comment by sefeng211** [comment]
Sorry for the late reply.

I don't have `projectile-enable-caching` set to `t`, it's `nil`. 

`projectile-completion-system` says `ivy`

I am unable to set `counsel-projectile-find-file-matcher` to `nil` because emacs returns `Value nil does not match type choice of counsel-projectile-find-file-matter`

**Comment by ericdanan** [comment]
Sorry, you indeed cannot set `counsel-projectile-find-file-matcher` to `nil`, I meant set it to `'ivy--re-filter` (the default ivy matcher, so that should give the same performance as `projectile-find-file`. Also is `counsel-projectile-sort-files` at its default `nil` value?

Setting `projectile-enable-caching` to `t` should increase performance, especially for large projects, but that should affect `projectile-find-file` and `counsel-projectile-find-file` equally.

**Comment by ericdanan** [comment]
Hello,

Are you still affected by this issue? I just downloaded the `firefox` source code from https://github.com/mozilla/gecko-dev and `projectile-find-file` and `counsel-projectile-find-file` perform similarly for me: about 12s when `projectile-enable-caching` is `nil` and almost instantly once cached when `t`.

**Comment by sefeng211** [comment]
Hi! 

Yeah, I still have the same issue. I've set `projectile-enable-caching` to `t`, but `projectile-find-file` still outperforms `counsel-projectile-find-file` significantly.

**Comment by ericdanan** [comment]
Can you try setting `counsel-projectile-find-file-matcher` to `'ivy--re-filter` (the default ivy matcher,
so that should give the same performance as `projectile-find-file`) and making sure `counsel-projectile-sort-files` is at its default `nil` value?

**Comment by sefeng211** [comment]
So that indeed boosts the performance of `counsel-projectile-sort-files`, however, I still feel `projectile-find-file` performs better here..

**Comment by ericdanan** [comment]
OK let's try to measure the difference. Can you open a buffer from the project (say `Makefile.in`) then evaluate each of these two forms from the scratch buffer with `C-j`, press `Enter` as soon as you see candidates in the minibuffer, and report the respective times?

``` elisp
(with-current-buffer "Makefile.in"
  (benchmark-run 1
    (projectile-invalidate-cache nil)
    (projectile-find-file)))

```

``` elisp
(with-current-buffer "Makefile.in"
  (benchmark-run 1
    (let ((counsel-projectile-sort-files nil)
          (counsel-projectile-find-file-matcher #'ivy--re-filter))
      (projectile-invalidate-cache nil)
      (counsel-projectile-find-file))))

```

**Comment by sefeng211** [comment]
Sorry, I don't use Emacs anymore and I don't think I'll provide more inputs here. So I am closing this. 

Appreciate for help!

**Comment by egbulmer** [comment]
FYI @ericdanan I also experienced this issue on one of our projects (110k files) and setting `'ivy--re-filter` resolved the problem for me.

**Comment by ianyepan** [comment]
I found that setting `counsel-projectile-find-file` to `ivy--regex-plus` instead of `ivy--regex-fuzzy` in `ivy-re-builders-alist` greatly improved the performance.
