### ISSUE TITLE
counsel-projectile ignore directories

### ISSUE THREAD

**Issue by SreenivasVRao** [ericdanan/counsel-projectile#156]
Hi, thank you so much for this package - I love the enhancements for using projectile!

I'm trying to set some ignore directories and file types - and I came across #57 

My issue is that I don't use `rg` or `ag` - so I'm not sure which functions counsel-projectile calls. I would like it to use projectile's ignore list. Any tips?

Thanks :)

**Comment by ericdanan** [comment]
Hi, thanks. Did you try `counsel-projectile-grep` or `counsel-projectile-git-grep`?

**Comment by SreenivasVRao** [comment]
Hi Eric - I'm not talking about git-grep here. That works perfectly. 

counsel-projectile-grep hangs for me though after I type in the first argument. I think it's because the interactive grep starts searching the entire file system.


However, that's not my issue. I'm using counsel-projectile to bring up the project buffer list (somewhat similar to projectile-find-file...)


Maybe the problem is with projectile-find-file since that doesn't seem to respect entries in projectile-ignored-directories...

I think this is the actual issue
https://github.com/bbatsov/projectile/issues/1250

**Comment by ericdanan** [comment]
`counsel-projectile-find-file` will show the same files as `projectile-find-file` (`counsel-projectile` just adds the project open buffers to the project files). So indeed the solution would be to fix the projectile issue. If that is an option for you you could also try changing your `projectile-indexing-method`.
