### ISSUE TITLE
counsel-projectile-modify-action stopped working recently

### ISSUE THREAD

**Issue by DamienCassou** [ericdanan/counsel-projectile#159]
I have this in my configuration:

```emacs
(counsel-projectile-modify-action
     'counsel-projectile-switch-project-action
     '((default counsel-projectile-switch-project-action-vc)))
```

This has worked fine for years but has stopped working 2 days ago because of the Ivy fix to https://github.com/abo-abo/swiper/pull/2585.

/cc @tylerware and @abo-abo.

**Comment by abo-abo** [comment]
@ericdanan Please let me know if there's a fix needed on Ivy's side.

**Comment by DamienCassou** [comment]
This got fixed by https://github.com/abo-abo/swiper/pull/2590.

**Comment by ericdanan** [comment]
Thanks everyone!
