### ISSUE TITLE
Recursive filtering on ag/greg output

### ISSUE THREAD

**Issue by fdr** [ericdanan/counsel-projectile#162]
Hello, thanks for counsel-projectile.

I use it quite happily, but find that of all the replacements that C-p s s (ag search) is perhaps the least like its replaced functionality. Sometimes I find it quite useful to have the search results be a full buffer, so I can use narrowing and search on the file name involved, including use of swiper.

So, one option is: how can I disable this one chunk of counsel-projectile functionality?

That said, I do often find the abbreviated form that counsel-projectile exposes as useful, so an even better approach would be to keep the initial functionality as it is now (ten lines of so of continuously refreshed search) and then have a key to pop the results into a full frame that I can then use swiper/etc.

Thoughts?

**Comment by ericdanan** [comment]
Hello,

From the minibuffer you can press `C-c C-o` (`ivy-occur`) to open a buffer with all matching candidates. Is this what you are looking for?

**Comment by fdr** [comment]
Yes! I had no idea. Thanks for teaching me.
