### ISSUE TITLE
FR: support previews like counsel-switch-buffer

### ISSUE THREAD

**Issue by aspiers** [ericdanan/counsel-projectile#163]
`counsel-switch-buffer` has a really awesome feature where it previews buffers which are currently selected in the minibuffer, even before switching to them.  It would be great if `counsel-projectile-switch-to-buffer` and maybe other functions could also do this.

**Comment by ericdanan** [comment]
Thanks for the suggestion. I am very short of time currently but will try to implement it.

**Comment by aspiers** [comment]
Amazing, thank you so much in advance for anything you can manage!

**Comment by ericdanan** [comment]
I just implemented this, please test.

**Comment by aspiers** [comment]
Works beautifully - awesome work!!

**Comment by ericdanan** [comment]
Note that I just improved the preview functionality and also made it optional, you need to set `counsel-projectile-preview-buffers` to a non-nil value if you want it. If you do so then `counsel-projectile` will also preview non-visited files if `counsel-switch-buffer-preview-virtual-buffers` is non-nil (which is the default).

**Comment by aspiers** [comment]
Sounds very cool, I'll give it a try!

**Comment by Andsbf** [comment]
just "installed/tweaked" it today, 

@ericdanan thanks for another GREAT feature!
