### ISSUE TITLE
counsel-projectile-grep not prompting for additional options

### ISSUE THREAD

**Issue by fixmaker** [ericdanan/counsel-projectile#165]
According to the documentation for `counsel-projectile-grep`:

> OPTIONS-OR-CMD, if non-nil, is a string containing either
additional options to be passed to grep, or an alternative git
grep command. It is read from the minibuffer if the function is
called with a prefix argument.

However when I run `C-u M-x counsel-projectile-grep` it **does not prompt for any options** in the minibuffer (the search prompt is shown immediately, regardless of whether the command is run with a prefix argument).

**Comment by ashton314** [comment]
Seems to be happening with `counsel-projectile-rg` as well

**Comment by ericdanan** [comment]
Thanks. The issue was affecting `counsel-projectile-grep/git-grep/ag-rg` for various reasons. It should now hopefully all be working, both when calling these commands from a project buffer and when switching project. Please test.

**Comment by fixmaker** [comment]
Thanks for maintaining a great package.

This seems to be working now _when called from within a project buffer_, but when called from _outside_ of a project buffer then (as expected) the minibuffer will prompt for the name of the project to use, but there is no prompt for any grep options.

**Comment by ericdanan** [comment]
When you select the project, you need to `C-u RET` as the prefix you initially passed to `counsel-projectile-rg` is gone at that point.
