### ISSUE TITLE
FR: Add command "counsel-projectile-recent-file"

### ISSUE THREAD

**Issue by ludwignagelhus** [ericdanan/counsel-projectile#168]
Projectile provides the command "projectile-recent-file". A `counsel`-ed version of this would be really nice. I am relatively new to emacs and lisp, so creating a pull request is probably going to take a long time for me. If no one volunteers to write a pull request I might give it a go eventually.

**Comment by ericdanan** [comment]
To be sure, are you talking about `projectile-recentf`?

**Comment by ludwignagelhus** [comment]
Yes. My bad, I misremembered the name of the function. Jumping to a recently used file in the same project is one of the functions I use the most, so I was a little surprised to see it doesn't exist. Currently I am using `counsel-buffer-or-recentf`, which does the job nicely, but the entire file path is used. Is there perhaps some other package other people use for this use case, which I am not aware of?

**Comment by ericdanan** [comment]
Since counsel-projectile loads projectile, the command `projectile-recentf` is actually available (you can `C-c p e` from inside a project to jump to a recent file). Could you clarify what do you think a "counsel-ed version" would add to it? Or pehaps you simply would like it to be added as an action in `counsel-projectile-switch-project`?

**Comment by ludwignagelhus** [comment]
I would like for it to display the recently used filenames using `ivy` (instead of the default menu where multiple choices appear on a single line, and are delimited by pipes), and to display paths relative to the root of the project.

**Comment by Gleek** [comment]
Can you try after setting `(setq projectile-completion-system 'ivy)`
