### ISSUE TITLE
unable to modify default action

### ISSUE THREAD

**Issue by kujohn** [ericdanan/counsel-projectile#169]
I am trying to modify the default action so `find-file-action` would always open in new window. The issue was that the Action was not found. Any ideas?

``` elisp
(counsel-projectile-modify-action
 'counsel-projectile-find-file-action
 '((default counsel-projectile-action-other-window)))
```

**Comment by ericdanan** [comment]
It is not found because `counsel-projectile-action-other-window` does not belong to `counsel-projectile-action-other-window`. If you want to modify the default action for `counsel-projectile-find-file`, it should be:

``` elisp
(counsel-projectile-modify-action
 'counsel-projectile-find-file-action
 '((default counsel-projectile-find-file-action-other-window)))
```

For `counsel-projectile` it should be:

``` elisp
(counsel-projectile-modify-action
 'counsel-projectile-action
 '((default counsel-projectile-action-other-window)))
```

**Comment by kujohn** [comment]
Thank you, that works!
