### ISSUE TITLE
projectile-switch-project-hook not called

### ISSUE THREAD

**Issue by rakanalh** [ericdanan/counsel-projectile#17]
Seems like the `projectile-switch-project-hook` doesn't get called when switching to project or when opening a file in a specific project.
Does this package handle this?

**Comment by ericdanan** [comment]
`counsel-projectile-switch-project` (and hence `counsel-projectile`) relies on `projectile-switch-project-by-name` to switch project, so it should run both `projectile-before-switch-project-hook` and `projectile-after-switch-project-hook` just like `projectile-switch-project` does. But AFAIK there is no such thing as `projectile-switch-project-hook`.

Could you check if the hook gets called with `projectile-switch-project` but not with `counsel-projectile-switch-project`?

**Comment by rakanalh** [comment]
I searched projectile project and it seems they renamed the hook... weird because i switched from helm only yesterday and the hook was working.

But i also added projectile-after-switch-project-hook and this is what happens:
If i call `projectile-switch-project` the hook is called. But previously i also had it call the hook in case i open a file in a project without having to switch to project manually, isn't that the case?

**Comment by ericdanan** [comment]
I'm not sure about helm-projectile, but in projectile it is not the case AFAICT: `projectile-before-switch-project-hook` and `projectile-after-switch-project-hook` are only called when switching project, and there is a different hook, `projectile-find-file-hook`, which is called when opening a file with `projectile-find-file`. counsel-projectile mimics this behavior.
