### ISSUE TITLE
Switching project now makes current buffer a blank *counsel-projectile* buffer

### ISSUE THREAD

**Issue by ianyepan** [ericdanan/counsel-projectile#171]
As titled, after the latest upgrade, when switching project with counsel-projectile-switch-project, the current buffer I was working on turns into a blank buffer with the buffer name \*counsel-projectile\*. I wonder if this was some intended feature, or an unintentional side effect since the last commites.

**Comment by ericdanan** [comment]
Thanks, indeed it was an unintended side effect of the previous commit implement a preview functionality in `counsel-projectile-switch-buffer`, that would show up when you switch to project having no open buffer. The buffer itself always existed but was not meant to be displayed. It should be fixed now, let me know if not.

Note that I also made the preview functionality optional, you need to set `counsel-projectile-preview-buffers` to a non-nil value if you want it. If you do so then `counsel-projectile` will also preview non-visited files if `counsel-switch-buffer-preview-virtual-buffers` is non-nil (which is the default).
