### ISSUE TITLE
Issue with `counsel-projectile-rg` on melpa-stable

### ISSUE THREAD

**Issue by myTerminal** [ericdanan/counsel-projectile#180]
Thank you for the package!

I've switched from `melpa` to `melpa-stable` a while back and have started seeing this error with `counsel-projectile-rg`:

    counsel-projectile-rg: Wrong type argument: stringp, ("rg" "-M" "240" "--with-filename" "--no-heading" "--line-number" "--color" "never" "%s")

I kept ignoring the problem and used `counsel-projectile-grep` instead and when I finally investigated, I found that the code for version 0.3.1 on `melpa-stable` is way older than the tip of the `master` branch and there have been a lot of fixes specifically around `counsel-projectile-rg`.

Do you plan to make another release so that the latest version is available at `melpa-stable`?

**Comment by ericdanan** [comment]
Hi, I just tagged a new release, should be on melpa stable in a few hours. That should fix your issues (let me know if not).
