### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (void-variable ivy--display-transformers-list)

### ISSUE THREAD

**Issue by bennfocus** [ericdanan/counsel-projectile#181]
ivy--display-transformers-list was removed in ivy-0.13.4,

there is a `ivy--display-transformers-alist`

**Comment by ericdanan** [comment]
The change of variable was made some time ago. Perhaps you are using the version from melpa-stable, which is older than that. I just made a new release, melpa-stable should have it in a few hours and your issue should be fixed (let me know if not).

**Comment by bennfocus** [comment]
Thanks! @ericdanan
