### ISSUE TITLE
counsel-projectile-ag shows no results for some projects

### ISSUE THREAD

**Issue by DarthFennec** [ericdanan/counsel-projectile#25]
`counsel-projectile-ag` always displays `No matches found`, regardless of what I search, in some projects. Running `counsel-ag` from the project root finds the correct results for the same searches. In other projects, `counsel-projectile-ag` works as expected. Whether it works or not seems to depend on what kind of project I'm in. I've only tested with a few different projects:

- A Gradle project using Git works
- A Maven project using Git works
- A generic project using Git works
- A Haskell Stack project with no vcs doesn't work
- A generic project with no vcs doesn't work

It seems to be related to the vcs. From looking at the code, it seems that the `--ignore` options are only used when the vcs is not Git, which makes me think that there might be a problem with that ...

Now that I look at it further, it seems that the arguments to the `--ignore` options aren't being escaped properly. `counsel-ag` uses `shell-command-to-string` to run the `ag` command, which appears to feed the command through the default shell, which will prematurely expand wildcards before they reach `ag`. This would cause some files to show up in the results when they aren't supposed to ... but, it seems like one of the patterns in `grep-find-ignored-files`, which you use to build the `--ignore` options, is `.#*`, which matches the correct files in `bash`, but in my `zsh` it expands to all files in the current directory. So that would explain why I'm not getting any results ...

So, it seems that this ignore list should be properly escaped, using `shell-quote-argument` on each element, or something like that.

**Comment by ericdanan** [comment]
Thank you for pointing this out and sorry for the slow reply. I will look into the issue but I am completely out of time at the moment so it may take a couple of weeks before I can get to it.
