### ISSUE TITLE
Current file appears after switching projects

### ISSUE THREAD

**Issue by raxod502** [ericdanan/counsel-projectile#32]
Say I've got a project `foo` with files `foo-a`, `foo-b`, `foo-c`, and a project `bar` with files `bar-a`, `bar-b`, `bar-c`, and say I'm currently editing file `foo-a`. When I press `C-c p SPC` I see:

```
foo-a
foo-b
foo-c
```

Then when I press `M-SPC` I see:

```
foo
bar
```

Now let's say I select `bar`. What I expect to see next is:

```
bar-a
bar-b
bar-c
```

But what I actually see is:

```
foo-a
bar-a
bar-b
bar-c
```

In other words, when I am selecting a file in another project, *the current file is always shown at the top of the list*, **even if it is not part of that project**!

My best guess for why this happens is:

* the default action after switching projects is `counsel-projectile`, so
* not only files but also buffers for the new project are shown, but
* as soon as the new project is selected, the "current project" is changed, so
* the current buffer suddenly looks like it belongs to the new project, and
* it gets shown in the list.

I can reproduce this with `emacs -Q` loading just `counsel-projectile` and its dependencies.

**Comment by ericdanan** [comment]
Thanks for reporting this issue. It appeared after commit https://github.com/bbatsov/projectile/commit/72a8be50b9e6d4c23a178f777043e67794fc9728 in projectile.

Before this commit, projectile called the switch project action from a temp buffer with `default-directory` let-bound to the project to switch to. After the commit it is no longer the case: the action is now called from the buffer from which you switch project, with `default-directory` let-bound to the new project in this buffer. Hence while switching, the initial buffer is incorrectly considered as belonging to the new project, as you guessed.

Actually the commit above was more or less restoring projectile's former behavior. The temp buffer thing had been introduced by pull request https://github.com/bbatsov/projectile/pull/1051 that I submitted.

So I'll have to figure out how to adapt counsel-projectile to this change. Problem is, I can't find the time at the moment. I quickly looked at the issue that the commit was fixing but I didn't really understand why my PR had caused the issue. I see you were involved in the issue discussion, so you may understand better than me. Anyway, any idea you might have about this would be much appreciated. Perhaps a starting point would to check whether the issue also affects helm-projectile, and if not understand how it is addressed there.

**Comment by raxod502** [comment]
My current workaround is to just disable the listing of buffers in the file selection menu, i.e. `(setq projectile-switch-project-action #'counsel-projectile-find-file)`. This also prevents the crippling lag that crops up due to checking the project of all the buffers I have open.

**Comment by ericdanan** [comment]
The issue should be solved now, please let me know if it is not. There is still an issue of `counsel-projectile` being slow that I will have to look into though.

**Comment by raxod502** [comment]
Maybe https://github.com/ericdanan/counsel-projectile/commit/d55966f113042cb146635b793fee099fce171972 fixed that?

Although since I prefer to show only files and not buffers in `projectile-switch-project-action`, the change does not affect me anymore.

**Comment by ericdanan** [comment]
This commit partially solved the issue, but for very large projects `counsel-projectile` is still a bit slow. I think this is because when a project file is currently visited by a buffer, it only displays the buffer and not the file. When there are many files, it is time-consuming to test for each one whether or not it is currently visited.

If your default action is `counsel-projectile-find-file` then you are not affected because this simply uses `projectile-current-project-files`.

**Comment by ericdanan** [comment]
FYI, I improved the performance of `counsel-projectile`, it should be about as fast as `counsel-projectile-find-file` now except for very lare projects with a lot of open buffers.
