### ISSUE TITLE
Perhaps tag a stable release?

### ISSUE THREAD

**Issue by mdorman** [ericdanan/counsel-projectile#36]
There haven't been any updates in a couple of months---if the project is stable, perhaps you could tag a release so melpa-stable will pick it up.

**Comment by cowboyd** [comment]
Would love a release. All you need to do is push a git tag `v0.1.0` to the repo and melpa will take care of the rest.

**Comment by ericdanan** [comment]
I'm closing this as this is a duplicate of #21. So let's continue the discussion there (I just posted a comment).
