### ISSUE TITLE
Allow to enter counsel-projectile-switch-project from counsel-projectile-find-files

### ISSUE THREAD

**Issue by thblt** [ericdanan/counsel-projectile#37]
I sometimes end up in counsel-projectile-find-file in the wrong project, either because: 

 - I was in the wrong buffer.
 - A buffer outside all projects became associated with a project for some reason.

It would be nice that when listing files in a project, it was possible to press `M-o`, a binding (let's say `p`) to switch projects instead.  The current way is to enter `C-g C-p p SPC` (abort, enter counsel-projectile-switch-project).  The proposed solution would be to simply run `M-o p`.

Thanks!

**Comment by raxod502** [comment]
Can't you already do this by pressing `M-SPC` in the `counsel-projectile-find-file` UI?

**Comment by ericdanan** [comment]
@raxod502 correct, thanks.
