### ISSUE TITLE
How does one restrict file types or subdirectories counsel-projectile-ag?

### ISSUE THREAD

**Issue by strom** [ericdanan/counsel-projectile#40]
I'd like to be able to restrict my counsel-projectile-ag search to all *.js files or anything in "css/" in my project. Is this possible?

**Comment by akhramov** [comment]
Hi, I couldn't find a way to restrict file types, also. So I wrote a hack-around.

```elisp
(defun counsel-projectile-ag-spike (old-text)
  (let ((original-counsel-ag (symbol-function 'counsel-ag)))
    (cl-letf (((symbol-function 'counsel-ag)
               #'(lambda (_ &rest args) (apply original-counsel-ag old-text args))))
    (ivy-read "Type: " nil
            :action
            (lambda (type)
              (counsel-projectile-ag (format "--%s" type)))))))

;; Bind type-filtering to C-t.
(setf counsel-ag-map
      (let ((map (make-sparse-keymap)))
        (set-keymap-parent map counsel-ag-map)
        (define-key map (kbd "C-t")
          (lambda ()
            (interactive)
            (ivy-exit-with-action (lambda (_) (counsel-projectile-ag-spike ivy--old-text)))))
        map))
```

Basically, this code binds type-filtering to "C-t", and forces [counsel-projectile-ag](https://github.com/ericdanan/counsel-projectile/blob/master/counsel-projectile.el#L211) to pass type argument as well as "initial-input" to `counsel-ag`.

There might be tons of improvements. For instance, one can utilize `ag --list-file-types` to form the completion-list for type input. 

Hope it helps you.

**Comment by ericdanan** [comment]
If I understand correctly, you can do this directly by using the optional variable `OPTIONS` of `counsel-projectile-ag`, which is a string of options to be passed to ag. If you call `counsel-projectile-ag` with a prefix arg then you will be prompted for this string in the minibuffer. So `C-u C-c p s s` then typing `--js` and `RET` should restrict matches to `.js` files. Similarly, `C-u C-c p s s` then typing `-G css/` and `RET` should restrict matches to files inside the `css` directory. Please let me know if I am missing the point.

**Comment by strom** [comment]
@ericdanan Yes, that's what I was looking for! I wasn't aware you could call a function with prefix args. Thank you!

In my case, I had a different key binding `s-F` to run counsel-projectile-ag. Calling it with prefix `C-u` worked. I.E., `C-u s-F` allowed me to enter in the options you described.
