### ISSUE TITLE
counsel-projectile--file-list very slow with large project

### ISSUE THREAD

**Issue by ambihelical** [ericdanan/counsel-projectile#41]
I have a large project (A non-public project) with about 420K files.  I noticed that counsel-projectile-find-file was quite slow, taking about 15s to show the list of files, so I experimented.  I replaced `counsel-projectile--file-list` with `projectile-current-project-files` and somewhat surprisingly, the list of files appears almost instantly. 
The drawback of course is the extra functionality added by `counsel-projectile--file-list` is not present, but it actually makes the package usable for larger projects.   Maybe `counsel-projectile--file-list` can gracefully degrade for large projects?  I'm not sure what would be a good solution, but it is an issue.  

Here is my modified function: 
```
;; version of counsel-projectile-find-file which uses
;; projectile-current-project-files instead of the fontified
;; counsel-projectile--file-list
;; To see if performance is better
(defun me:counsel-projectile-find-file (&optional arg)
  (interactive "P")
  (projectile-maybe-invalidate-cache arg)
  (ivy-read (projectile-prepend-project-name "Find file: ")
            (projectile-current-project-files)
            :matcher #'counsel--find-file-matcher
            :require-match t
            :keymap counsel-projectile-map
            :action #'counsel-projectile--find-file-action
            :caller 'counsel-projectile-find-file))

```

**Comment by ambihelical** [comment]
I noticed while writing the report that #31 may be the same issue.

**Comment by ericdanan** [comment]
See #44
