### ISSUE TITLE
counsel-projectile-rg in a non-git project outputs Error messages for ignore files

### ISSUE THREAD

**Issue by dsdshcym** [ericdanan/counsel-projectile#46]
![image](https://user-images.githubusercontent.com/4723751/28964779-d0812ba8-7940-11e7-8696-3d23a1df7b94.png)

It's related to the ignore option counsel-projectile-rg added.

**Comment by chaoyi** [comment]
it seems "--ignore-files" is not the right switch to use

change
 (concat "--ignore-files " (shell-quote-argument i))
to
 (concat "--glob " (shell-quote-argument (concat "!" i)))
should fix the problem

**Comment by dsdshcym** [comment]
@chaoyi Thanks for your help! Didn't see that option in rg's manual. 
I've submitted a PR for the fix.

If you want to submit a PR by your self, feel free to let me know, and I'll close my PR

**Comment by hisnawi** [comment]
I came across this bug as well. Is there a time frame when we will see this committed?
