### ISSUE TITLE
counsel-projectile-switch-project shows the current buffer as candidate after selecting a project

### ISSUE THREAD

**Issue by r-darwish** [ericdanan/counsel-projectile#48]
Steps to reproduce:

1. Launch Emacs
2. Hit `C-c p p`
3. Select a project and press enter

Expected Result:
Ivy should only display the list of files from the selected project.

Actual Result:
`*scratch*` appears at the top of the list followed by files from the selected project

This behaviour isn't reproduced when counsel-projectile is off and projectile is set to use Ivy as a completion system

**Comment by ericdanan** [comment]
Hi, thanks for reporting. Same issue as #32. See there for details and a workaround. I will have to modify the project-switching mechanism.

**Comment by ericdanan** [comment]
Please test, it should work now with the latest commit.
