### ISSUE TITLE
Make ivy-set-actions customizable

### ISSUE THREAD

**Issue by raxod502** [ericdanan/counsel-projectile#49]
Currently, if I don't like the value passed to `ivy-set-actions` for `counsel-projectile-switch-project`, my only future-proof option for overriding it is forking `counsel-projectile`. Perhaps we could have a customizable alist that affected the generation of the data structure passed to `ivy-set-action`.

**Comment by ericdanan** [comment]
I'm not sure I understand, wouldn't it work to add

```
(ivy-set-actions
  'counsel-projectile-switch-project
  '(<your custom action list>))
```

to your init file?

**Comment by raxod502** [comment]
Of course, but that's not future-proof, as it requires copying the entire definition into my init-file, and then there is no way to know if it has changed upstream (plus I don't like version-controlling other people's code).

A trivial change which would improve the situation would be to put the actions list into a variable, because then I could maintain it using [`el-patch`](https://github.com/raxod502/el-patch), thus eliminating concerns about future-proofing.

**Comment by ericdanan** [comment]
I see.

So I made a `defun` for each action and put the action list into a `defvar`. That should make it easier to manipulate the actions. I'm not sure the `defvar` is so useful since you could always get the list with `(plist-get ivy--actions-list 'counsel-projectile-switch-project)`, but it shouldn't hurt anyway.

Let me know how it works for you.

**Comment by raxod502** [comment]
That's beautiful. I don't know if it's the ideal interface but it's definitely good enough for the scope of `counsel-projectile`.

I might suggest making the action functions public (`-` instead of `--`) though, if they're meant to be usable in customization.

**Comment by ericdanan** [comment]
I renamed all action and transformer functions to avoid `--`. Also created `defvar`s for the other command's action lists (eg `counsel-projectile-find-file`), although they are merely 1-elements lists right now.

I guess it would more user-friendly to change these `defvar`s to `defcustom`s, and I think it is then possible to have `ivy-set-actions` be called automatically every time the variable is customized, although I have never done it. Or perhaps even call `ivy-set-actions` inside `counsel-projectile-switch-project` (or other commands), but I'm not sure if it's a good way to proceed.

**Comment by raxod502** [comment]
Indeed, I think the "right" way to do it is to write a function `counsel-projectile-update-ivy-actions`, which calls `ivy-set-actions` using the current value of `counsel-projectile-switch-project-actions` (and similarly for the other actions alists), and then call that function from the `:set` attribute, like the defcustom for `show-paren-delay`:

```
(defcustom show-paren-delay 0.125
  "Time in seconds to delay before showing a matching paren.
If you change this without using customize while `show-paren-mode' is
active, you must toggle the mode off and on again for this to take effect."
  :type '(number :tag "seconds")
  :initialize 'custom-initialize-default
  :set (lambda (sym val)
	 (if (not show-paren-mode)
	     (set sym val)
	   (show-paren-mode -1)
	   (set sym val)
	   (show-paren-mode 1))))
```

Either way, I love what you have done with the other actions lists. They look fantastic now.

**Comment by ericdanan** [comment]
Thanks! I will implement this at some point.

**Comment by ericdanan** [comment]
FYI I just made the defcustoms. Thanks again for pointing me in the right direction, I didn't know about the `:set` attribute.
