### ISSUE TITLE
How to add projectile-run-term action?

### ISSUE THREAD

**Issue by sooheon** [ericdanan/counsel-projectile#5]
I've tried adding this as an action, but projectile-run-term

```
("t" (lambda (dir)
              (let ((projectile-switch-project-action 'projectile-run-term))
                (projectile-switch-project-by-name dir arg)))
        "start term for project")
```

But projectile-run-term expects another arg (the term program to run), and I'm not sure how to give it this arg.

**Comment by sooheon** [comment]
Solved :) for posterity, you do it as follows:

```
("t" (lambda (dir)
              (let ((projectile-switch-project-action (lambda () (projectile-run-term "/usr/local/bin/fish"))))
                (projectile-switch-project-by-name dir arg)))
        "start term for project")
```

**Comment by ericdanan** [comment]
good :)

**Comment by sooheon** [comment]
@ericdanan Do you know how to set an action to forward to projectile-ag? I want to select a project from the list then be met with another instance of ivy prompting for ag search string.

**Comment by ericdanan** [comment]
I don't use this myself. Looking at `projectile-ag`, I would say something like this:

```
("a" (lambda (dir)
              (let ((projectile-switch-project-action (lambda () (call-interactively 'projectile-ag))))
                (projectile-switch-project-by-name dir arg)))
        "search with ag")
```

Does it work?
