### ISSUE TITLE
issues with ag searches

### ISSUE THREAD

**Issue by vidjuheffex** [ericdanan/counsel-projectile#51]
if I use projectiles-ag and search, I get a bunch of results
if I use counsel-projectile, I'm not getting any results. I hit enter and nothing...

I'm on windows 64 using the emacs64 build on chocolatey.
Let me know what I can provide to help.

**Comment by ericdanan** [comment]
It works for me. I guess you mean counsel-projectile-ag instead of counsel-projectile (by the way you dont need to hit enter, the results should show up in the minibuffer as soon as you input a few characters). Do you get results if you call counsel-ag from the project root?

**Comment by vidjuheffex** [comment]
no, there seems to be an issue with counsel-ag on Windows, and the developers suggestion to "use a real os" on a similar thread, has me looking for alternatives, so I don't think its an issue in your package, but it is a documented issue on counsel. Thanks!

**Comment by ericdanan** [comment]
I see. In case you're interested, it works for me with cygwin emacs-w32 on windows 10.

**Comment by ericdanan** [comment]
Just saw this, perhaps it can solve your problem with using `counsel-ag` on windows:

https://github.com/abo-abo/swiper/pull/1221

**Comment by vidjuheffex** [comment]
TIme to give the ivy/counself route one more shot, thanks
