### ISSUE TITLE
Support ag's `--path-to-ignore` flag

### ISSUE THREAD

**Issue by andrewhampton** [ericdanan/counsel-projectile#56]
There's current support for including the .gitignore, but there are many files in my companies git projects I would like to ignore that are checked into github. One the command line, I use `--path-to-ignore` to skip these files when I use ag, and I would like to be able to use that here too. Right now, I'm just manually editing the counsel-projectile.el to be:

```lisp
             (options
              (concat options " "
                      (mapconcat (lambda (i)
                                   (concat "--ignore " (shell-quote-argument i)))
                                 ignored
                                 " ")
                      " --path-to-ignore ~/.agignore ")))

```

However, this is overwritten each time I upgrade to the latest version.

**Comment by ericdanan** [comment]
Hello,

Does it work if you call `counsel-projectile-ag` with a `C-u` prefix arg and then enter `--path-to-ignore ~/.agignore` in the options prompt, or equivalently if you call `(counsel-projectile-ag "--path-to-ignore ~/.agignore")`?

**Comment by andrewhampton** [comment]
@ericdanan it turned out I had an unnecessary trailing * in my `.agignore` file that was causing the problem. That in combination with `alias ag="ag --path-to-ignore ~/.agignore"` in my `.zshrc` fixed my problem.
