### ISSUE TITLE
Ignore regexp for counsel-projectile-ag? 

### ISSUE THREAD

**Issue by hicksy994** [ericdanan/counsel-projectile#57]
Is there a way to ignore certain paths when running counsel-projectile-ag? I don't want to search the build dir for example.

**Comment by ericdanan** [comment]
Yes, there is an optional argument `OPTIONS` to pass any option you like to `ag`. For instance:

```
(counsel-projectile-ag "--ignore some/path")
```

You can call `counsel-projectile-ag` with a `C-u` prefix to input the options string interactively.

If you want to setup `counsel-projectile-ag` to systematically ignore certain paths, you could instead add these paths to the variables `projectile-ignored-files-rel` and/or `projectile-ignored-directories-rel`.

**Comment by amosbird** [comment]
Um, can we just reuse the pattern of `.projectile`? I have this ignore list but it doesn't affect `counsel-projectile-ag/rg`'s behavior.

```
-/contrib
-/c6
-/c6build
-/chdbg
-/clickhouse
-/dbg
-/rel
-compile_commands.json
-/debian
```

**Comment by ericdanan** [comment]
Can you turn off counsel-projectile and let me know if it works with
projectile-ag?

**Comment by amosbird** [comment]
the output of `projectile-ag` is quite weird. I cannot see any file names. The ag command is `ag --ignore \*.elc --ignore \*.pyc --ignore \*.o --literal --group --line-number --column --color --color-match 30\;43 --color-path 1\;32 --smart-case --stats -- BackgroundProcessingPool .`

**Comment by ericdanan** [comment]
Doesn't seem to obey your `.projectile` file either.

Can you call these three functions from a project buffer and copy the output?

```
(projectile-project-vcs)
(projectile-ignored-files-rel)
(projectile-ignored-directories-rel)
```

**Comment by amosbird** [comment]
they are 
```
git
(".DS_Store" "Icon" "TAGS")
(".idea/" ".ensime_cache/" ".eunit/" ".git/" ".hg/" ".fslckout/" "_FOSSIL_/" ".bzr/" "_darcs/" ".tox/" ".svn/" ".stack-work/" "../../.emacs.d/.local/" ".sync/" "contrib/" "c6/" "c6build/" "chdbg/" "clickhouse/" "dbg/" "rel/" "debian/")
```

**Comment by ericdanan** [comment]
So, `projectile-ignored-directories-rel` correctly parses your `.projectile` file, but `projectile-ag` and `counsel-projectile-ag` do not pay attention to the `.projectile` file for `git` projects. This is because `git` has its own `.gitignore` file and `ag` parses it natively. I would suggest to use `.gitignore` instead of `.projectile` for such projects.

**Comment by amosbird** [comment]
Hmm, some directories are not suitable for gitignore, such as test and contrib folders.

**Comment by ericdanan** [comment]
Can you update to latest commit, set `counsel-projectile-ag-use-gitignore-only` to `nil` and let me know if it works?

**Comment by amosbird** [comment]
@ericdanan thanks! it works perfectly.

**Comment by ericdanan** [comment]
I just pushed another commit and that variable is no longer there, the behavior you want is now the default.

This means `counsel-projectile-ag` and `counsel-projectile-rg` work a bit differently from their projectile analogues, but I think it is more consistent with `counsel-projectile-find-file` (or equivalently `projectile-find-file`) in the sense that all these functions (hopefully) now look at the same set of files in a project.

When you call `counsel-projectile-ag` or `counsel-projectile-rg` with a prefix arg you have full control on the options to be passed to `ag` or `rg` including which paths are ignored.

**Comment by ericdanan** [comment]
Please open a new issue if needed.
