### ISSUE TITLE
Keep a binding for projectile-ag?

### ISSUE THREAD

**Issue by Schnouki** [ericdanan/counsel-projectile#59]
Hi,

From time to time I still like to use `projectile-ag` without counsel. For example when I want to use `wgrep` 😉 
Would it be possible to remap `projectile-ag` to `s S` (for instance) so it can still be used?

Thanks!

**Comment by ericdanan** [comment]
Yes, you should be able to do it by evaluating this after loading counsel-projectile:

```
(define-key projectile-command-map (kbd "s S") #'projectile-ag)
```

**Comment by Schnouki** [comment]
That would be the obvious way, but since `projectile-ag` is remapped to `counsel-projectile-ag` in the `projectile-command-map`, my extra binding is remapped as well...

At the moment I'm using a binding in the global map, which works well, but I don't like this solution that much. A bit ugly in my opinion to add a package-specific binding in the global map :)

Any idea about a better way to do this?

**Comment by ericdanan** [comment]
I don't know if you'll find it better, but the following works for me:

```
(define-key projectile-command-map (kbd "s S") (lambda ()
						 (interactive)
						 (call-interactively 'projectile-ag)))
```

**Comment by ericdanan** [comment]
With the new version `0.2` that I just pushed, there is more flexibility to achieve what you want.

Please look at the readme, and in particular the upgrading section, about important changes before upgrading.

Then you can put the followint in your init file:

```emacs-lisp
(define-key counsel-projectile-mode-map [remap projectile-ag] nil)
(define-key counsel-projectile-command-map (kbd "s S") 'projectile-ag)
(define-key counsel-projectile-command-map (kbd "s s") 'counsel-projectile-ag)
```

**Comment by ericdanan** [comment]
Please reopen if needed.
