### ISSUE TITLE
Using either ag or rg on dos line-encoded files shows ^M characters at the buffer

### ISSUE THREAD

**Issue by r-darwish** [ericdanan/counsel-projectile#63]
When using either ag or rg to search something in a DOS line-encoded project, `^M` characters appear in the buffer. This breaks [wgrep](https://github.com/mhayashi1120/Emacs-wgrep)'s functionality.

**Comment by ericdanan** [comment]
`counsel-projectile-ag` and `counsel-projectile-rg` rely on `counsel-ag` and `counsel-rg`, respectively, to perform the search. So this is not likely to be an issue with counsel-projectile. In other word, you should observe the same behavior when calling `counsel-ag` or `counsel-rg`. My guess is that this not a problem with these latter commands either and you should get the same behavior if you call `ag` or `rg` from a terminal.

I don't know if `ag` or `rg` has an option to specify the line ending, but if so then you can call `counsel-projectile-ag` or `counsel-projectile-rg` with a `C-u` prefix to pass this option.

**Comment by r-darwish** [comment]
`counsel-rg` behaves the same. I'll open this ticket in the counsel project.
