### ISSUE TITLE
Problem on projectile-mode-hook

### ISSUE THREAD

**Issue by zhengpd** [ericdanan/counsel-projectile#64]
On recent change the `counsel-projectile-on` is replaced by `counsel-projectile-mode`. I enable counsel-projectile on projectile-mode-hook before, so the first thing I did after upgrade is using counsel-projectile-mode in the hook, but actually this will cause `nesting exceeds max-lisp-eval-depth` error. I think maybe it's worth to mention in README that `counsel-projectile-mode` will call `projectile-mode` automatically.

**Comment by ericdanan** [comment]
It is actually mentioned in the Getting Started section. Perhaps you just overlooked it, but if you didn't find the explanation clear enough let me know.

**Comment by zhengpd** [comment]
Saw it.
