### ISSUE TITLE
Fails package-lint

### ISSUE THREAD

**Issue by mdorman** [ericdanan/counsel-projectile#65]
If I load `counsel-projectile.el` and run `package-lint-current-buffer`, I get the following errors:
```
502:33: error: You should depend on (emacs "24.4") if you need `string-remove-prefix'.
264:37: error: You should depend on (emacs "24.4") if you need `string-remove-prefix'.
831:41: error: You should depend on (emacs "24") if you need `pcase'.
262:31: error: You should depend on (emacs "24") if you need `string-prefix-p'.
192:7: error: You should depend on (emacs "24") if you need `pcase'.
9:24: error: Package counsel is not installable.
9:43: error: Package projectile is not installable.
1:1: error: package.el cannot parse this buffer: Package lacks a file header
```
Obviously the one about packages not being installable is specific to my environment, but the others aren't.

It would appear the last item is simply the lack of a third `;` on the first line, which means that it doesn't actually match the `package.el` specification.

**Comment by ericdanan** [comment]
Thanks a lot! I don't know how I removed this semicolumn in the first line, just added it back. Also avoided `string-remove-prefix` so no need to depend on emacs 24.4 (both counsel and projectile work with 24.3).

Hope everything is in order now.

**Comment by ericdanan** [comment]
Please reopen if needed.
