### ISSUE TITLE
Pressing Enter on a counsel-projectile-ag result appends path to the current file

### ISSUE THREAD

**Issue by ashutoshrishi** [ericdanan/counsel-projectile#66]
This issue suddenly popped up, I don't know what I upgraded. I am already using `(counsel-projectile-mode)` instead of the older command.

When I search for a word in my project (using `counsel-projectile-ag`) from a project file `project/apps/foo/lib/foo.ex` and get matching results like:

```
- apps/bar/lib/bar.ex:6 - ...
- ...
```

If I select `apps/bar/lib/bar.ex` and press Enter, I am taken to a missing file `project/apps/foo/lib/apps/bar/lib/bar.ex` instead of `project/apps/bar/lib/bar.ex`. This was not the behaviour before. 

How can I debug this further?

**Comment by ericdanan** [comment]
This is due to a recent change in the counsel package. See abo-abo/swiper#1392.

**Comment by ericdanan** [comment]
Should work now if you update counsel, please reopen if not.

**Comment by ashutoshrishi** [comment]
It works now, thanks!
