### ISSUE TITLE
Insert a default search symbol for counsel-projectile-rg

### ISSUE THREAD

**Issue by hisnawi** [ericdanan/counsel-projectile#68]
counsel-projectile-rg is my main function for search since it is much faster than ag. 
But I am envy of projectile-ag for having a default search (for symbol at point), also helm has this feature.

Is it possible to add this enhancement?

**Comment by ericdanan** [comment]
You can hit `M-n` from the minibuffer to insert the output of `ivy-thing-at-point` (this works in all ivy commands).

If you want this to be pre-inserted systematically, then you can customize the variable `counsel-projectile-rg-initial-input`.

**Comment by hisnawi** [comment]
Thank you.
So this did not work:

`(setq counsel-projectile-rg-initial-input 'ivy-thing-at-point)
`
Am I doing it wrong?

**Comment by ericdanan** [comment]
Yes, the value should be a lisp form, not a function:
```emacs-lisp
(setq counsel-projectile-rg-initial-input '(ivy-thing-at-point))
```

Or if you want the exact same initial input as in `projectile-ag` :
```emacs-lisp
(setq counsel-projectile-rg-initial-input '(projectile-symbol-or-selection-at-point))
```

**Comment by hisnawi** [comment]
That worked. Thanks!

**Comment by hisnawi** [comment]
I have one more question, After clicking on one of the search results, if I want to go back to search results with ivy-resume it start from the very beginning. It does not continue from the point I selected one of the results. Is there a way to remember that point in the search buffer?
