### ISSUE TITLE
How this package is different from stock `ivy` support in `projectile`?

### ISSUE THREAD

**Issue by srustamo** [ericdanan/counsel-projectile#7]
`projectile` seems to have `ivy-read` completion support, with `(projectile-completion-system (quote ivy))`.

The stock behaviour a bit broken (as reported [here](https://github.com/abo-abo/swiper/issues/264#issuecomment-240940668)), still, how this package is different from the stock ivy support?

**Comment by ericdanan** [comment]
The difference is that this package also takes advantage of `ivy`'s mechanism to propose several actions to choose from.

For instance, if you call the function `counsel-projectile`, you can select a project with `ivy` completion and you can then choose from a (customizable) list of actions to apply to the selected project (find file, find buffer, open magit...). If instead you set up `projectile` to use `ivy` completion and call the function `projectile-switch-project`, you can also select a project with `ivy` completion suppurt but you can then only apply the default action to the selected project (find file by default).

**Comment by srustamo** [comment]
Thanks.
