### ISSUE TITLE
How to change face attribute of the `counsel-projectile-find-file` result

### ISSUE THREAD

**Issue by jilen** [ericdanan/counsel-projectile#70]
Result of `counsel-projectile-find-file`, it is not readable

![screenshot from 2018-01-17 19-06-15](https://user-images.githubusercontent.com/546573/35039671-844a298c-fbb9-11e7-8702-12d7511e9429.png)

Result of `counsel-projectile-ag`
![screenshot from 2018-01-17 19-07-24](https://user-images.githubusercontent.com/546573/35039714-ad5754a8-fbb9-11e7-963a-af289aa2b522.png)

How can I make `counsel-projectile-find-file`'s result looks the same as `counsel-projectile-ag` ?

**Comment by ericdanan** [comment]
`counsel-projectile-find-file` displays project files that are not currently visited with the face `ivy-virtual` (same behavior as in `ivy-switch-buffer`). By default, this face inherits all attributes from `font-lock-builtin-face`. It seems that your emacs theme customizes either `font-lock-builtin-face`, or `ivy-virtual` directly, so you should set one of these faces to something more readable (if you need help with this please let me know what is your theme). The face used for file names in `counsel-projectile-ag` is `compilation-info`.

**Comment by jilen** [comment]
@ericdanan  Thanks very much, I am using [doom solarized light](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-solarized-light-theme.el), It seems only make that face slant.

I try to set foreground of `ivy-virtual` that fixes my problem, thanks again
