### ISSUE TITLE
Retain search results pointer after ivy-resume

### ISSUE THREAD

**Issue by hisnawi** [ericdanan/counsel-projectile#71]
After clicking on one of the search results for counsel-projectile-rg, if I want to go back to search results with ivy-resume it starts from the very beginning of the list. It does not continue from the point I selected one of the results. Is there a way to remember that point in the search buffer?

**Comment by ericdanan** [comment]
This is not currently possible. This is a general limitation of all ivy commands using a dynamic collection of candidates (such as `counsel-rg` on which `counsel-projectile-rg` relies). See abo-abo/swiper/issues/1095.
