### ISSUE TITLE
Option for searching only file names with counsel-projectile-find-file

### ISSUE THREAD

**Issue by crash-g** [ericdanan/counsel-projectile#72]
It would be nice if there was a way to only show matches based on the file name (not the whole file relative path) when using `counsel-projectile-find-file`. Maybe giving a prefix argument?
I usually get many unrelated results with the current behavior.

**Comment by ericdanan** [comment]
Thanks for the suggestion, you can now do
```emacs-lisp
(setq counsel-proejctile-find-file-matcher 'counsel-projectile-find-file-matcher-basename)
```
Please test.

**Comment by crash-g** [comment]
It works like a charm, thanks!
