### ISSUE TITLE
counsel-projectile causes files to disappear from projectile cache

### ISSUE THREAD

**Issue by tummychow** [ericdanan/counsel-projectile#74]
This is a bit of a strange one. Steps to repro:

1. create a new git repository with three files, `file1`, `file2`, `file3`
2. open emacs -Q and load counsel-projectile (package.el, straight.el, what have you)
3. `(setq projectile-enable-caching t)` and then `counsel-projectile-mode`
4. `C-x C-f` and navigate to `file1`, this will add it to the known projects list. then `kill-this-buffer`
5. `C-c p SPC`, open `file1`
6. repeat with the other two files (don't kill any buffers)
7. `kill-this-buffer` (kills `file3`)
8. `kill-this-buffer` (kills `file2`)
9. `counsel-projectile` again and look at the list of files

expected behavior: all three files would appear. actual behavior: `file1` appears (because it's still an open buffer), `file3` appears (as a file), but `file2` is completely missing. If you purge the cache by adding a prefix argument, the second file will reappear. Another very interesting quirk about this bug: I can't seem to reproduce it if I use `counsel-projectile-find-file` in step 6 instead of `counsel-projectile`.

**Comment by ericdanan** [comment]
Thank you for the detailed report. Should be fixed now, please test.
