### ISSUE TITLE
Grep does not work with tramp.

### ISSUE THREAD

**Issue by proofit404** [ericdanan/counsel-projectile#79]
I open repository remotely using tramp. All projectile commands operate normally. But when I try to use grep command from this package I see:

    fatal: Not a git repository (or any of the parent directories): .git

Grep command from projectile itself works correctly.

**Comment by ericdanan** [comment]
Do you have `projectile-use-git-grep` set to `t`? If so then `counsel-projectile-grep` simply calls `counsel-git-grep`. Can you test if `counsel-git-grep` gives the same error?

**Comment by proofit404** [comment]
Yes, I can confirm that problem occurs inside `counsel-git-grep`.

Thanks!
