### ISSUE TITLE
Feature request: kill-buffer action for counsel-projectile-switch-to-buffer

### ISSUE THREAD

**Issue by CSRaghunandan** [ericdanan/counsel-projectile#81]
Similar to how we can kill buffer with `M-o k` n `ivy-switch-buffer`. Likewise, we can assign `C-c C-k` to kill buffer like `ivy-switch-buffer` does

**Comment by ericdanan** [comment]
Thanks, please test (it should work for both `counsel-projectile-switch-to-buffer` and `counsel-projectile`, either with `M-o k` or `C-c C-k`).

**Comment by CSRaghunandan** [comment]
Thank you :)
Works as expected
