### ISSUE TITLE
How to change key bindings?

### ISSUE THREAD

**Issue by Opioid** [ericdanan/counsel-projectile#83]
I want to change some key-bindings for counsel-projectile. Specifically I only want a single search command bound to _C-c p s_. For this I tried:

> (use-package counsel-projectile
>   :bind (("C-c p s" . counsel-projectile-rg))  
>   :config
>   (counsel-projectile-mode)
>   (unbind-key "C-c p s s" counsel-projectile-mode-map)
>   (unbind-key "C-c p s g" counsel-projectile-mode-map)
>   (unbind-key "C-c p s r" counsel-projectile-mode-map))

However, this results in all counsel-projectile keybindings being disabled. If I remove the _:bind (...)_ line the keybindings stay intact, including the ones I actually want to unbind.
Maybe something different is required because counsel-projectile keybindings in turn overwrite projectile keybindings?

**Comment by ericdanan** [comment]
The following should work:

```emacs-lisp
(define-key counsel-projectile-command-map (kbd "s") 'counsel-projectile-rg)
```

**Comment by Opioid** [comment]
Works perfectly!
