### ISSUE TITLE
Make counsel-projectile-mode respect projectile-command-map keymap rebinding

### ISSUE THREAD

**Issue by technician77** [ericdanan/counsel-projectile#84]
Below is my code to init projectile. Is there a way that counsel-projectile-mode reads the redifition of the projectile-command-map keymap binding and uses the defintion as a base for its key replacements?

```
(use-package projectile
  :bind-keymap
  ("C-s-p" . projectile-command-map)
  :config
  (define-key projectile-mode-map projectile-keymap-prefix nil)
  (setq projectile-completion-system 'ivy)
  (setq projectile-enable-caching t)
  (projectile-mode)
  :delight
  projectile-mode " 📋")
```

**Comment by ericdanan** [comment]
Is there a specific reason why you don't simply set `projectile-keymap-prefix` to modify the keybinding for `projectile-command-map`? I'm not a use-package user, but I think the following should work and be respected by counsel-projectile (please let me know if it's not):

```emacs-lisp
(use-package projectile
  :init
  (setq projectile-keymap-prefix "C-s-p")
  :config
  (setq projectile-completion-system 'ivy)
  (setq projectile-enable-caching t)
  (projectile-mode)
  :delight
  projectile-mode " 📋")
```

I'm not sure how counsel-projectile could respect the way you rebind `projectile-command-map` outside of `projectile-mode-map` (`projectile-command-map` is not a command so I don't think it can be remapped directly).

**Comment by technician77** [comment]
I'd like to lazy load as much packages as possible. Use-package does this if it knows when to load the package. Main triggers I use are by keybindings or commands. Besides that I had syntax problems with the projectile-keymap-prefix variable. The same problems as your suggestion. Luckily I found a workaround on stackexchange. So this works:
`    (setq projectile-keymap-prefix (kbd "C-s-p"))`
As you predicted it works correctly with counsel-projectile-mode. So the only problem that remains is lazy-loading. I can apply `:defert t` to projectile, but not on counsel-projectile. If I do so it does not replace the commands when I call the projectile-prefix.

**Comment by ericdanan** [comment]
I see, then you could perhaps keep your `:bind-keymap` allowing lazy loading of projectile but also set `projectile-keymap-prefix` to the correct binding so that it will be picked up when you load counsel-projectile:

```emacs-lisp
(use-package projectile
  :bind-keymap
  ("C-s-p" . projectile-command-map)
  :init
  (setq projectile-keymap-prefix (kbd "C-s-p"))
  :config
  (setq projectile-completion-system 'ivy)
  (setq projectile-enable-caching t)
  (projectile-mode)
  :delight
  projectile-mode " 📋")
```

Does that work?

**Comment by technician77** [comment]
Yes, I can use either this or `:defer t`. But lazy-loading projectile is not the problem. The problem is to lazy-load counsel-projectile. This might be a lost cause. I would need to "tell" use package to load it when projectile is called via prefix. I tried to use the same `:bind-keymap ("C-s-p" . projectile-command-map)` 
on counsel-projectile but that does not work. Counsel-projectile takes it time to load, not sure why, maybe it causes projectile to load and time for that is added to counsel-projectile.
```
  (use-package projectile
    :bind-keymap
    ("C-s-p" . projectile-command-map)
    :init
    (setq projectile-keymap-prefix (kbd "C-s-p"))
    :config
    (setq projectile-completion-system 'ivy)
    (setq projectile-enable-caching t)
    (projectile-mode)
    :delight
    projectile-mode " 📋")
  (use-package counsel-projectile
    :config
    (counsel-projectile-mode))
```

```
Configuring package projectile...done
Configuring package counsel-projectile...done
Loading package counsel-projectile...done (4.685s)
```

**Comment by ericdanan** [comment]
I tested on a clean emacs 25.3 with only use-package and counsel-projectile (and their dependencies) installed though MELPA. The following works for me:

```emacs-lisp
(use-package projectile
    :bind-keymap
    ("C-c q" . projectile-command-map)
    :init
    (setq projectile-keymap-prefix (kbd "C-c q"))
    :config
    (setq projectile-completion-system 'ivy)
    (setq projectile-enable-caching t)
    (projectile-mode)
    :delight
    projectile-mode " 📋")
(use-package counsel-projectile
    :bind-keymap
    ("C-c q" . counsel-projectile-command-map)
    :config
    (counsel-projectile-mode))
```

I'm using `C-c q` as an example because `C-s-p` doesn't seem to do anything (I'm not sure what it means actually). Neither projectile nor counsel-projectile are loaded at startup. If I `C-c q p` then both are loaded (this doesn't take long, less than 0.1s per package I presume since use-package doesn't tell me how long) and `counsel-projectile-switch-project` is called. If I comment out the `use-package` declaration for counsel-projectile and restart then it still works as expected and `C-c q p` calls `projectile-switch-project`.

Can you try it?

**Comment by technician77** [comment]
Not working for me. First I use `GNU Emacs 26.0.91 (build 1, x86_64-w64-mingw32) of 2018-01-22`. Then `C-s-p` means "Hold Control+Super then press p". But even using your keycord it does not work. It seems Counsel-projectile is not triggered to be loaded. It does not show up in messages, even after `C-c q p` it is not loaded. See which key screenshot and help hint. It feels like the definition of the keymap in projectile blocks it for being a trigger in counsel-projectile.

By the way I'm pretty sure all this hassle would not exist if counsel-projectile would just be a part of projectile.

```
counsel-projectile-command-map is an interactive autoloaded Lisp function in
‘counsel-projectile.el’.

[Arg list not available until function definition is loaded.]

Not documented.
```


![image](https://user-images.githubusercontent.com/18722291/38062361-c62f3f24-32f3-11e8-8c7d-3158c799f65a.png)

This is how it looks if lazy-load trigger is removed from counsel-projectile (using my key binding)
![image](https://user-images.githubusercontent.com/18722291/38063031-6512cacc-32f7-11e8-8b5c-fdee4fe8b6ac.png)

**Comment by ericdanan** [comment]
That is strange, I downloaded the same version of emacs as you and it does work for me. Can you try with a clean emacs with only use-package and counsel-projectile installed from MELPA? Here is the full content of the init file I have:

```emacs-lisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)

(setq use-package-verbose t)
(use-package projectile
    :bind-keymap
    ("C-c q" . projectile-command-map)
    :init
    (setq projectile-keymap-prefix (kbd "C-c q"))
    :config
    (setq projectile-completion-system 'ivy)
    (setq projectile-enable-caching t)
    (projectile-mode)
    :delight
    projectile-mode " 📋")
(use-package counsel-projectile
    :bind-keymap
    ("C-c q" . counsel-projectile-command-map)
    :config
    (counsel-projectile-mode))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (counsel-projectile use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by ericdanan** [comment]
Hello,
Are you still affected by this issue?

**Comment by technician77** [comment]
No, I'm not. I now use Emacs 26.1RC1 and for this or some unknown reason the problem disappeard. I can now use the bind-keymap for projectile and counsel-projectile and both are lazy loaded correctly.

**Comment by AlynxZhou** [comment]
Hi, I got the same issue, my config looks like this:

```
(use-package counsel
  :ensure t
  :config
  (counsel-mode 1)
  :bind (("C-c g" . counsel-git)
	 ("C-c j" . counsel-git-grep)
	 ("C-c k" . counsel-rg)
	 ("C-c l" . counsel-locate)
	 ;; ("C-S-o" . counsel-rhythmbox)
         :map minibuffer-local-map
         ("C-r" . counsel-minibuffer-history)))

(use-package counsel-projectile
  :ensure t
  :after (counsel projectile)
  :config
  (counsel-projectile-mode 1))

;; others

(use-package projectile
  :ensure t
  :config
  (projectile-mode 1)
  :bind (("M-s" . projectile-ripgrep))
  ;; See <https://github.com/jwiegley/use-package#binding-to-keymaps>.
  :bind-keymap (("C-c p" . projectile-command-map))
  :custom
  (projectile-completion-system 'ivy)
  (projectile-cache-file
   (locate-user-emacs-file ".local/cache/projectile.cache"))
  (projectile-known-projects-file
   (locate-user-emacs-file ".local/projectile-bookmarks.eld")))
```

Now I can lazy load projectile, but counsel-projectile is not loaded (when I press something like `C-c p s r`, the non-counsel-projectile version is called), is there anything wrong?

I also opened an issue for use-package: <https://github.com/jwiegley/use-package/issues/976>
