### ISSUE TITLE
buffer information

### ISSUE THREAD

**Issue by zer09** [ericdanan/counsel-projectile#85]
Does ```counsel-projectile-switch-to-buffer``` have feature like ```ivy-enable-advanced-buffer-information```? Adding more information on the buffer list.

**Comment by ericdanan** [comment]
Thanks,, please test.

`counsel-projectile-switch-to-buffer` (and `counsel-projectile`) should now display buffers in the same way as `ivy-switch-buffer` even if you enable the ivy-rich package (or change the latter command's transformer function in any other way).

I didn't know about `ivy-enable-advanced-buffer-information` but if I understand correctly it is a spacemacs-specific way of enabling the ivy-rich package.
