### ISSUE TITLE
"require: Symbol’s value as variable is void: ivy-height-alist"

### ISSUE THREAD

**Issue by squarepegsys** [ericdanan/counsel-projectile#86]
I just installed `counsel` from MELPA and then installed `counsel-projectile` and it won't run -- it gives the error 
 > require: Symbol’s value as variable is void: ivy-height-alist

**Comment by ericdanan** [comment]
It does not seem to me to be related to counsel-projectile, but my guess is that you need to update ivy. The variable ivy-height-alist was introduced 21 days ago by commit abo-abo/swiper@1181d0f7acb9e77a15fa7e62cb1027979185c853. It is defined in ivy and used in counsel. If your ivy version is older than that commit and your counsel verion is newer, that could explain the error.

**Comment by squarepegsys** [comment]
I just installed ivy by installing counsel just before the error.

This morning I removed ivy, swiper, and counsel, restarted Emacs and then installed ivy first and then counsel... and then that worked. Which is awfully strange.
