### ISSUE TITLE
counsel-projectile-find-dir does not open directory in the current window

### ISSUE THREAD

**Issue by occisn** [ericdanan/counsel-projectile#88]
According to documentation, in the course of **counsel-projectile-find-dir** command (C-c p d), "o" should open directory in the _current_ window, and "j" should open directory in _other_ window.

On my computer, this is not the case: both open directory in _other_ window.

I think that the problem comes from the below definition:

```
(counsel-projectile--defcustom-action
 'counsel-projectile-find-dir
 '(1
   ("o" counsel-projectile-find-dir-action-other-window
    "current window")
   ("j" counsel-projectile-find-dir-action-other-window
    "other window")
   ("m" counsel-projectile-find-file-action-find-file-manually
    "find file manually")
   ("p" (lambda (_) (counsel-projectile-switch-project))
    "switch project"))
 'counsel-projectile)
```

I think that the **counsel-projectile-find-dir-action-other-window** on the same line as "o" should be modified into **counsel-projectile-find-dir-action**.

I have made this modification on my computer and recompiled. It works now as expected.

**Comment by ericdanan** [comment]
Thanks, there was obviously a mistake.
