### ISSUE TITLE
Change default binding for counsel-projectile-switch-project

### ISSUE THREAD

**Issue by CSRaghunandan** [ericdanan/counsel-projectile#9]
Hello, I'm an mac user and I use `alfred` as a my default launcher which is bound to `M-SPC`. Maybe you could change the default key binding for `counsel-projectile-switch-project` which is bound to `M-SPC` when in `ivy-minibuffer` for `counsel-projectile`?
 I wouldn't want to change the default key for `alfred` as its too ingrained in my muscle memory.

ps. I'm not sure how i can change the key bindings when only in `counsel-projectile`.
I know I can do this 

```
:map ivy-minibuffer-map
(("C-c C-p" . counsel-projectile-switch-project))
```

But this would add it to `ivy` and not `counsel-projectile`. But I see there is a `counsel-projectile-map`.  I tried to do this :- 

```
:map counsel-projectile-map
(("C-c C-p" . counsel-projectile-switch-project))
```

But this doesnt seem to work.

**Comment by ericdanan** [comment]
Hello.

When you say it does not seem to work, do you mean that <kbd>C-c C-p</kbd> has not effect, or that <kbd>M-SPC</kbd> still has the undesired effect for you?

My understanding is that you are using use-package and your `:map` declaration adds the <kbd>C-c C-p</kbd> binding but does not remove the <kbd>M-SPC</kbd> one, so either one of the two should call `counsel-projectile-drop-to-switch-project`. To get rid of the latter one, I think you need to add

```
(unbind-key "M-SPC" counsel-projectile-map)
```

in the `:config` section of the use-package form for `counsel-projectile`.

In any case, I just made the binding customizable. So you should now be able to obtain what you want by simply adding

```
(setq counsel-projectile-drop-to-switch-project-binding "C-c C-p"
```

in the `:init` section.

Let me know if you are still having problems.

**Comment by CSRaghunandan** [comment]
@ericdanan  I'll check it out and report back to you after melpa refresh is done. So far, I don't see the updated package in melpa.

**Comment by CSRaghunandan** [comment]
Okay, I added (setq counsel-projectile-drop-to-switch-project-binding "C-c C-p"), but there seems to be a problem. I get the error **`command attempted to use minibuffer while in minibuffer`**

**Comment by ericdanan** [comment]
I cant reproduce the error. Is it when you hit <kbd>C-c C-p</kbd> that you get it? Do you also get it with <kbd>M-SPC</kbd> if you remove the `setq`?

This error apparently happens when you have the variable `enable-recursive-minibuffers` set to `nil` (the default) and try to launch a new minibuffer command without exiting the current one. But `counsel-projectile-drop-to-switch-buffer` exits `counsel-projectile-switch-buffer` before calling `counsel-projectile-switch-project`, so I don't understand what happens.

**Comment by CSRaghunandan** [comment]
Hey, it's working for me now. I've no idea what was wrong before. 
I'll close the issue then. Thanks a lot for your help

**Comment by ericdanan** [comment]
OK perfect.
