### ISSUE TITLE
counsel-projectile-find-file-dwim

### ISSUE THREAD

**Issue by dcherian** [ericdanan/counsel-projectile#90]
Can you add a dwim version of `counsel-projectile-find-file` please?

See `helm-projectile` version here: https://github.com/bbatsov/helm-projectile/blob/74349fc9132502af2b2e6ca9a51185ae4c9391b4/helm-projectile.el#L761

**Comment by ericdanan** [comment]
Please update to latest version and try `counsel-projectile-find-file-dwim`.

It is slightly different in that if there is single candidate, it is still displayed so that one of the actions of `counsel-projectile-find-file` can be chosen.
