### ISSUE TITLE
Projectile prefix change

### ISSUE THREAD

**Issue by hotpxl** [ericdanan/counsel-projectile#91]
counsel-projectile share the same keybinding prefix as projectile.
recently projectile changed that from C-c p to C-c C-p (https://github.com/bbatsov/projectile/commit/e2762f20d65a4372d4eed766d1c71b09e9e4ef8c)

The documentation might need to be updated

**Comment by bbo2adwuff** [comment]
After that there were even more changes and the last one breaks counsel-projectile.

`projectile-keymap-prefix` is obsolete now, see
https://github.com/bbatsov/projectile/commit/9c6e9813abec6e067c659e9107bf356086a95e04

**Comment by hotpxl** [comment]
😢

**Comment by ericdanan** [comment]
Thanks. Please update to latest version, don't forget to bind `projectile-command-map` as explained in the projectile readme, and let me know if you still have issues.

I've removed the counsel-projectile keymaps (`counsel-projectile-mode-map` and `counsel-projectile-command-map`). All key bindings are now installed through the native projectile keymaps (`projectile-mode-map` and `projectile-command-map`). There's a new variable `counsel-projectile-key-bindings` that can be customized to tweak the counsel-projectile bindings.
