### ISSUE TITLE
let: Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by rakanalh** [ericdanan/counsel-projectile#93]
Hello,

Recently, `counsel-projectil` and `counsel-projectile-ag` started throwing this error when invoked. It seems to be related to upgrading this package and/or upgrading `counsel` and `projectile`.

Versions:
```
counsel            20180808.1527
projectile         20180808.833
counsel-projectile 20180731.2305
```

**Comment by hlissner** [comment]
Here's a backtrace of the issue that another user reported to me:

```lisp
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  define-key((keymap) nil counsel-projectile-command-map)
  byte-code("\301 \302\1\10\303#\210\302\1\304\305#\210\302\1\306\307#\210\302\1\310\311#\210\302\1\312\313#\210\302\1\314\315#\210\302\1\316\317#\210\211\207" [projectile-keymap-prefix make-sparse-keymap define-key counsel-projectile-command-map [remap projectile-find-file] counsel-projectile-find-file [remap projectile-find-dir] counsel-projectile-find-dir [remap projectile-switch-to-buffer] counsel-projectile-switch-to-buffer [remap projectile-grep] counsel-projectile-grep [remap projectile-ag] counsel-projectile-ag [remap projectile-switch-project] counsel-projectile-switch-project] 5)
  (defvar counsel-projectile-mode-map (byte-code "\301 \302\1\10\303#\210\302\1\304\305#\210\302\1\306\307#\210\302\1\310\311#\210\302\1\312\313#\210\302\1\314\315#\210\302\1\316\317#\210\211\207" [projectile-keymap-prefix make-sparse-keymap define-key counsel-projectile-command-map [remap projectile-find-file] counsel-projectile-find-file [remap projectile-find-dir] counsel-projectile-find-dir [remap projectile-switch-to-buffer] counsel-projectile-switch-to-buffer [remap projectile-grep] counsel-projectile-grep [remap projectile-ag] counsel-projectile-ag [remap projectile-switch-project] counsel-projectile-switch-project] 5) ("/home/dale/.emacs.d/.local/packages/elpa/counsel-projectile-20180731.2305/counsel-projectile.elc" . 49046))
  call-interactively(counsel-projectile-find-file)
```

**Comment by julienXX** [comment]
Reverting projectile to commit `d2b808b1c5d3b895a48575093e7546d5637de17f` fixes the issue in the meantime.

**Comment by akash-akya** [comment]
Projectile deprecated `projectile-keymap-prefix` variable and reset to `nil`. see bbatsov/projectile@9c6e981. Similar to issue #91. check PR https://github.com/ericdanan/counsel-projectile/pull/92 for the fix.

**Comment by ericdanan** [comment]
Thanks. Please update to latest version, don't forget to bind `projectile-command-map` as explained in the projectile readme, and let me know if you still have issues.

I've removed the counsel-projectile keymaps (`counsel-projectile-mode-map` and `counsel-projectile-command-map`). All key bindings are now installed through the native projectile keymaps (`projectile-mode-map` and `projectile-command-map`). There's a new variable `counsel-projectile-key-bindings` that can be customized to tweak the counsel-projectile bindings.
