### ISSUE TITLE
VCS files not ignored

### ISSUE THREAD

**Issue by amake** [ericdanan/counsel-projectile#96]
With the latest version I find that VCS-ignored files are not ignored in `counsel-projectile-rg` queries.

I see that the cause is most likely the latest commit here: https://github.com/ericdanan/counsel-projectile/commit/ffc342bb7c9549d3ecefa12b8981874a6ef33f25

I understand that you want to delegate ignoring/including to projectile so that its ignore/include facilities can affect `counsel-projectile-*` queries. However as things currently are I don't think the behavior is quite what was intended.

Projectile does provide facilities for getting a list of files ignored by VCS settings: `projectile-get-repo-ignored-files`. However this function does not feed into the ignore settings used by `counsel-projectile-rg` or `-ag` at all; instead what is used is the union of `projectile-ignored-files-rel` and `projectile-ignored-directories-rel`. This is not equivalent to `projectile-get-repo-ignored-files`, and results in lots of things being included (not ignored), at least in my projects.

Perhaps the output of `projectile-get-repo-ignored-files` should be appended as well? Failing that, maybe it could be an option whether to ignore VCS files or not?

**Comment by amake** [comment]
In the meantime I've addressed the issue temporarily as so:

```
    (defun counsel-projectile-rg--ignore-vcs (old-function &rest args)
      (apply old-function `(,(concat (car args) " --ignore-vcs"))))
    (advice-add #'counsel-projectile-rg :around #'counsel-projectile-rg--ignore-vcs)
```

**Comment by DamienCassou** [comment]
I confirm the problem. I have to revert the latest commit to search in my project which contains many generated files that should not be passed to `rg` or Emacs freezes.

**Comment by ericdanan** [comment]
Sorry about the mess. Indeed I mistakenly thought that `projectile-ignored-files/directories-rel` would take care of VCS ignored files.

I reverted the commit and added another one that make `counsel-projectile-ag` and the like take into accound the project kept directories (those prefixed by `+` in the `.projectile` file) as well as the globally ignored file suffixes. This should make the searched files closer to the project files but there are still differences. In particular, VCS ignored files/directories that are unignored in the `.projectile` file are not searched and I don't see any straightforward solution to this.

Anyway, please let me know if you still face issues.

**Comment by manuel-uberti** [comment]
Thanks @ericdanan, it is fixed now.
