### ISSUE TITLE
How do I get `projectile-dired` to be in `counsel-projectile-switch-project`

### ISSUE THREAD

**Issue by brandon-arnold** [ericdanan/counsel-projectile#98]
This is similar to issue #62 but in that case, the action was already one of the options in the hydra menu. I liked having `projectile-dired` as a default switch action in projectile, viz. `(setq projectile-switch-project-action #'projectile-dired)`. But `M-o` within the ivy project list buffer shows this apparently isn't one of the options, and I'm really having trouble finagling the contents of `counsel-projectile-switch-project-action`. Any suggestions? Thanks!

**Comment by ericdanan** [comment]
Please update counsel-projectile, I just added a `projectile-dired` action to `counsel-projectile-switch-project`. You can call it with `M-o D`. You can do as in #62 if you want to make it the default action.

**Comment by brandon-arnold** [comment]
@ericdanan Beautimous, looks great. Thanks, Eric!

**Comment by brandon-arnold** [comment]
```
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((move counsel-projectile-switch-project-action-dired 1)
   (setkey counsel-projectile-switch-project-action-dired "D")
   (setkey counsel-projectile-switch-project-action " ")))
```
